import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _currentLanguage = 'English';
  String get currentLanguage => _currentLanguage;

  void changeLanguage(String language) {
    _currentLanguage = language;
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'skip': 'Skip',
      'welcome_title': 'Welcome to Our App',
      'welcome_subtitle': 'Discover a new way to connect and explore.\nGet started on your journey today!',
      'select_language': 'Select Language',
      'get_started': 'Get Started',
      'already_account': 'Already have an account? ',
      'log_in': 'Log In',
      'morocco': 'Morocco',
      'login_title': 'Log In',
      'login_subtitle': 'Welcome back! Please enter your details.',
      'email_phone_label': 'Email or Phone',
      'email_phone_hint': 'Enter your email or phone',
      'email_phone_error': 'Please enter your email or phone',
      'email_phone_invalid': 'Please enter a valid email or phone number',
      'password_label': 'Password',
      'password_hint': 'Enter your password',
      'password_error': 'Please enter your password',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot Password?',
      'login_button': 'Log In',
      'or_continue_with': 'Or continue with',
      'no_account': "Don't have an account? ",
      'sign_up': 'Sign Up',
      'login_success': 'Login successful!',
      'login_failed': 'Login failed. Please try again.',
      'sign_up_google': 'Sign up with Google',
      'sign_up_apple': 'Sign up with Apple',
      'sign_up_facebook': 'Sign up with Facebook',
      'forgot_password_title': 'Forgotten Password ?',
      'forgot_password_subtitle': 'Enter your email address to receive a password reset link.',
      'forgot_password_email_hint': 'Enter your email address',
      'send_reset_link': 'Send password reset link',
      'back_to_login': 'Back to login',
      'google_login_todo': 'Google Login - To be implemented with google_sign_in package',
      'apple_login_todo': 'Apple Login - To be implemented with sign_in_with_apple package',
      'facebook_login_todo': 'Facebook Login - To be implemented with flutter_facebook_auth package',
      'email_label': 'Email',
      'reset_link_sent': 'Reset link sent!',
      'reset_link_instructions': 'Please check your inbox mail and follow the instructions for the password reset link.',
      'create_account': 'Create Account',
      'full_name_label': 'Full Name',
      'full_name_hint': 'Enter your full name',
      'confirm_password_label': 'Confirm Password',
      'confirm_password_hint': 'Confirm your password',
      'travel_preferences_title': 'Travel Preferences',
      'duration_question': 'How long do you plan to travel ?',
      'duration_question_title': 'Travel Duration',
      'budget_question': 'What is your approximate budget ?',
      'budget_question_title': 'Budget Preference',
      'activities_question': 'What types of activities interest you ?',
      'activities_question_title': 'Activity Preferences',
      'accommodation_question': 'What type of accommodation do you prefer ?',
      'accommodation_question_title': 'Accommodation Type',
      'group_size_question': 'Who are you traveling with ?',
      'group_size_question_title': 'Group Size',
      'transportation_question_title': 'Transportation Preference',
      'multiple_choice_instruction': 'Select all the options that interest you',
      'Next': 'Next',
      'finish': 'Finish',
      'skip_button': 'Skip for later',
      'preferences_saved': '✅ Preferences saved successfully!',
      'preferences_saved_success': 'Preferences saved successfully!',
      'budget_economic': 'Economic (< 500 DH/day)',
      'budget_moderate': 'Moderate (500-1500 DH/day)',
      'budget_luxury': 'Luxurious (> 1500 DH/day)',
      'budget_friendly': 'Budget Friendly',
      'activity_culture': 'Culture & History',
      'activity_nature': 'Nature & Hiking',
      'activity_beach': 'Beach & Relaxation',
      'activity_adventure': 'Sports & Adventure',
      'activity_nightlife': 'Nightlife',
      'activity_gastronomy': 'Gastronomy',
      'accommodation_hotel': 'Hotel',
      'accommodation_hostel': 'Youth hostel',
      'accommodation_airbnb': 'Airbnb/Rental',
      'accommodation_camping': 'Camping',
      'accommodation_luxury_hotel': 'Luxury Hotel',
      'accommodation_boutique_hotel': 'Boutique Hotel',
      'accommodation_business_hotel': 'Business Hotel',
      'accommodation_budget_hotel': 'Budget Hotel',
      'accommodation_resort': 'Resort',
      'accommodation_riad': 'Riad',
      'accommodation_guesthouse': 'Guesthouse',
      'accommodation_apartment': 'Apartment',
      'accommodation_villa': 'Villa',
      'group_solo': 'Alone',
      'group_couple': 'As a couple',
      'group_family': 'With family',
      'group_friends': 'With friends',
      'group_family_kids': 'Family with Kids',
      'group_family_adults': 'Family with Adults',
      'group_friends_small': 'Small Group of Friends',
      'group_friends_large': 'Large Group of Friends',
      'transportation_flight': 'Flight',
      'transportation_car_rental': 'Car Rental',
      'transportation_private_driver': 'Private Driver',
      'transportation_public_transport': 'Public Transport',
      'transportation_train': 'Train',
      'transportation_taxi_ride_share': 'Taxi/Ride Share',
      'transportation_bicycle': 'Bicycle',
      'transportation_walking': 'Walking',
      'activity_culture_history': 'Culture & History',
      'activity_nature_wildlife': 'Nature & Wildlife',
      'activity_beach_water': 'Beach & Water Activities',
      'activity_adventure_sports': 'Adventure Sports',
      'activity_nightlife_entertainment': 'Nightlife & Entertainment',
      'activity_food_gastronomy': 'Food & Gastronomy',
      'activity_shopping': 'Shopping',
      'activity_wellness_spa': 'Wellness & Spa',
      'duration_unit': 'days',
      'home_title': 'Home',
      'home_welcome': 'Welcome',
      'home_search_hint': 'Search destinations, activities...',
      'home_recommendations_title': 'Recommendations Near You',
      'rec_park_title': 'Central Park',
      'rec_park_subtitle': 'A beautiful urban park with lakes and trails.',
      'rec_museum_title': 'Louvre Museum',
      'rec_museum_subtitle': 'Explore world-famous art collections.',
      'home_trending_title': 'Trending Destinations',
      'trending_paris_name': 'Paris',
      'trending_paris_subtitle': 'The City of Light awaits you.',
      'trending_kyoto_name': 'Kyoto',
      'trending_kyoto_subtitle': 'Discover ancient temples and gardens.',
      'home_seasonal_title': 'Seasonal Highlights',
      'seasonal_summer_title': 'Summer Escapes',
      'seasonal_summer_subtitle': 'Perfect spots for sun and sea.',
      'seasonal_autumn_title': 'Autumn Adventures',
      'seasonal_autumn_subtitle': 'Explore fall foliage and cool weather.',
      'home_featured_cities_title': 'Featured Cities',
      'city_nyc_name': 'New York City',
      'city_paris_name': 'Paris',
      'city_tokyo_name': 'Tokyo',
      'tag_business': 'Business',
      'tag_art_culture': 'Art & Culture',
      'tag_museums': 'Museums',
      'tag_cultural_attractions': 'Cultural Attractions',
      'tag_technology': 'Technology',
      'tag_traditional_culture': 'Traditional Culture',
      'reviews_label': 'reviews',
      'nav_home': 'Home',
      'nav_explore': 'Explore',
      'nav_products': 'Products',
      'nav_saved': 'Saved',
      'nav_profile': 'Profile',
      'explore_title': 'Explore Morocco',
      'explore_subtitle': 'Discover amazing destinations and activities',
      'products_title': 'Moroccan Products',
      'products_subtitle': 'Shop authentic handmade products',
      'saved_title': 'Your Saved Items',
      'saved_subtitle': 'Places, activities and products you saved',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'Manage your profile and preferences',
      'of': 'of',
      'guest_mode_info': 'Guest mode - Limited features',
      'guest_mode_description': 'You can explore the app, but some features require login',
      'login_required': 'Login Required',
      'login_required_message': 'This feature requires login. Would you like to login now?',
      'cancel': 'Cancel',
      'login': 'Login',
    },
    'Français': {
      'skip': 'Passer',
      'welcome_title': 'Bienvenue dans notre App',
      'welcome_subtitle': 'Découvrez une nouvelle façon de vous connecter et d\'explorer.\nCommencez votre voyage aujourd\'hui!',
      'select_language': 'Sélectionner la langue',
      'get_started': 'Commencer',
      'already_account': 'Vous avez déjà un compte? ',
      'log_in': 'Se connecter',
      'morocco': 'Maroc',
      'login_title': 'Se connecter',
      'login_subtitle': 'Bon retour! Veuillez entrer vos détails.',
      'email_phone_label': 'Email ou Téléphone',
      'email_phone_hint': 'Entrez votre email ou téléphone',
      'email_phone_error': 'Veuillez entrer votre email ou téléphone',
      'email_phone_invalid': 'Veuillez entrer un email ou numéro de téléphone valide',
      'password_label': 'Mot de passe',
      'password_hint': 'Entrez votre mot de passe',
      'password_error': 'Veuillez entrer votre mot de passe',
      'remember_me': 'Se souvenir de moi',
      'forgot_password': 'Mot de passe oublié?',
      'login_button': 'Se connecter',
      'or_continue_with': 'Ou continuer avec',
      'no_account': 'Vous n\'avez pas de compte? ',
      'sign_up': 'S\'inscrire',
      'login_success': 'Connexion réussie!',
      'login_failed': 'Échec de la connexion. Veuillez réessayer.',
      'sign_up_google': 'Se connecter avec Google',
      'sign_up_apple': 'Se connecter avec Apple',
      'sign_up_facebook': 'Se connecter avec Facebook',
      'forgot_password_title': 'Mot de passe oublié ?',
      'forgot_password_subtitle': 'Entrez votre adresse email pour recevoir un lien de réinitialisation.',
      'forgot_password_email_hint': 'Entrez votre adresse email',
      'send_reset_link': 'Envoyer le lien de réinitialisation',
      'back_to_login': 'Retour à la connexion',
      'google_login_todo': 'Connexion Google - À implémenter avec google_sign_in package',
      'apple_login_todo': 'Connexion Apple - À implémenter avec sign_in_with_apple package',
      'facebook_login_todo': 'Connexion Facebook - À implémenter avec flutter_facebook_auth package',
      'email_label': 'Email',
      'reset_link_sent': 'Lien de réinitialisation envoyé !',
      'reset_link_instructions': 'Veuillez vérifier votre boîte de réception et suivre les instructions du lien de réinitialisation du mot de passe.',
      'create_account': 'Créer un compte',
      'full_name_label': 'Nom complet',
      'full_name_hint': 'Entrez votre nom complet',
      'confirm_password_label': 'Confirmer le mot de passe',
      'confirm_password_hint': 'Confirmez votre mot de passe',
      'travel_preferences_title': 'Préférences de voyage',
      'duration_question': 'Combien de temps prévoyez-vous de voyager ?',
      'duration_question_title': 'Durée du voyage',
      'budget_question': 'Quel est votre budget approximatif ?',
      'budget_question_title': 'Préférence de budget',
      'activities_question': 'Quels types d\'activités vous intéressent ?',
      'activities_question_title': 'Préférences d\'activités',
      'accommodation_question': 'Quel type d\'hébergement préférez-vous ?',
      'accommodation_question_title': 'Type d\'hébergement',
      'group_size_question': 'Avec qui voyagez-vous ?',
      'group_size_question_title': 'Taille du groupe',
      'transportation_question_title': 'Préférence de transport',
      'multiple_choice_instruction': 'Sélectionnez toutes les options qui vous intéressent',
      'Next': 'Suivant',
      'finish': 'Terminer',
      'skip_button': 'Passer pour plus tard',
      'preferences_saved': '✅ Préférences enregistrées avec succès !',
      'preferences_saved_success': 'Préférences enregistrées avec succès !',
      'budget_economic': 'Économique (< 500 DH/jour)',
      'budget_moderate': 'Modéré (500-1500 DH/jour)',
      'budget_luxury': 'Luxueux (> 1500 DH/jour)',
      'budget_friendly': 'Économique',
      'activity_culture': 'Culture & Histoire',
      'activity_nature': 'Nature & Randonnée',
      'activity_beach': 'Plage & Détente',
      'activity_adventure': 'Sports & Aventure',
      'activity_nightlife': 'Vie nocturne',
      'activity_gastronomy': 'Gastronomie',
      'accommodation_hotel': 'Hôtel',
      'accommodation_hostel': 'Auberge de jeunesse',
      'accommodation_airbnb': 'Airbnb/Location',
      'accommodation_camping': 'Camping',
      'accommodation_luxury_hotel': 'Hôtel de luxe',
      'accommodation_boutique_hotel': 'Hôtel boutique',
      'accommodation_business_hotel': 'Hôtel d\'affaires',
      'accommodation_budget_hotel': 'Hôtel économique',
      'accommodation_resort': 'Station balnéaire',
      'accommodation_riad': 'Riad',
      'accommodation_guesthouse': 'Maison d\'hôtes',
      'accommodation_apartment': 'Appartement',
      'accommodation_villa': 'Villa',
      'group_solo': 'Seul',
      'group_couple': 'En couple',
      'group_family': 'Avec la famille',
      'group_friends': 'Avec des amis',
      'group_family_kids': 'Famille avec enfants',
      'group_family_adults': 'Famille avec adultes',
      'group_friends_small': 'Petit groupe d\'amis',
      'group_friends_large': 'Grand groupe d\'amis',
      'transportation_flight': 'Vol',
      'transportation_car_rental': 'Location de voiture',
      'transportation_private_driver': 'Chauffeur privé',
      'transportation_public_transport': 'Transport public',
      'transportation_train': 'Train',
      'transportation_taxi_ride_share': 'Taxi/Partage de trajet',
      'transportation_bicycle': 'Vélo',
      'transportation_walking': 'Marche',
      'activity_culture_history': 'Culture & Histoire',
      'activity_nature_wildlife': 'Nature & Faune',
      'activity_beach_water': 'Plage & Activités aquatiques',
      'activity_adventure_sports': 'Sports d\'aventure',
      'activity_nightlife_entertainment': 'Vie nocturne & Divertissement',
      'activity_food_gastronomy': 'Cuisine & Gastronomie',
      'activity_shopping': 'Shopping',
      'activity_wellness_spa': 'Bien-être & Spa',
      'duration_unit': 'jours',
      'home_title': 'Accueil',
      'home_welcome': 'Bienvenue',
      'home_search_hint': 'Rechercher des destinations, activités...',
      'home_recommendations_title': 'Recommandations près de chez vous',
      'rec_park_title': 'Parc Central',
      'rec_park_subtitle': 'Un magnifique parc urbain avec des lacs et des sentiers.',
      'rec_museum_title': 'Musée du Louvre',
      'rec_museum_subtitle': 'Explorez des collections d\'art mondialement célèbres.',
      'home_trending_title': 'Destinations tendances',
      'trending_paris_name': 'Paris',
      'trending_paris_subtitle': 'La Ville Lumière vous attend.',
      'trending_kyoto_name': 'Kyoto',
      'trending_kyoto_subtitle': 'Découvrez des temples et jardins anciens.',
      'home_seasonal_title': 'Points forts saisonniers',
      'seasonal_summer_title': 'Évasions estivales',
      'seasonal_summer_subtitle': 'Des spots parfaits pour le soleil et la mer.',
      'seasonal_autumn_title': 'Aventures automnales',
      'seasonal_autumn_subtitle': 'Explorez les feuillages d\'automne et le temps frais.',
      'home_featured_cities_title': 'Villes en vedette',
      'city_nyc_name': 'New York City',
      'city_paris_name': 'Paris',
      'city_tokyo_name': 'Tokyo',
      'tag_business': 'Affaires',
      'tag_art_culture': 'Art & Culture',
      'tag_museums': 'Musées',
      'tag_cultural_attractions': 'Attractions culturelles',
      'tag_technology': 'Technologie',
      'tag_traditional_culture': 'Culture traditionnelle',
      'reviews_label': 'avis',
      'nav_home': 'Accueil',
      'nav_explore': 'Explorer',
      'nav_products': 'Produits',
      'nav_saved': 'Enregistrés',
      'nav_profile': 'Profil',
      'explore_title': 'Explorer le Maroc',
      'explore_subtitle': 'Découvrez des destinations et activités incroyables',
      'products_title': 'Produits Marocains',
      'products_subtitle': 'Achetez des produits artisanaux authentiques',
      'saved_title': 'Vos Éléments Enregistrés',
      'saved_subtitle': 'Lieux, activités et produits que vous avez enregistrés',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'Gérez votre profil et vos préférences',
      'of': 'de',
      'guest_mode_info': 'Mode invité - Fonctionnalités limitées',
      'guest_mode_description': 'Vous pouvez explorer l\'application, mais certaines fonctionnalités nécessitent une connexion',
      'login_required': 'Connexion requise',
      'login_required_message': 'Cette fonctionnalité nécessite une connexion. Voulez-vous vous connecter maintenant ?',
      'cancel': 'Annuler',
      'login': 'Se connecter',
    },
    'العربية': {
      'skip': 'تخطي',
      'welcome_title': 'مرحباً بك في تطبيقنا',
      'welcome_subtitle': 'اكتشف طريقة جديدة للتواصل والاستكشاف.\nابدأ رحلتك اليوم!',
      'select_language': 'اختر اللغة',
      'get_started': 'ابدأ',
      'already_account': 'هل لديك حساب بالفعل؟ ',
      'log_in': 'تسجيل الدخول',
      'morocco': 'المغرب',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'مرحباً بعودتك! يرجى إدخال بياناتك.',
      'email_phone_label': 'البريد الإلكتروني أو الهاتف',
      'email_phone_hint': 'أدخل بريدك الإلكتروني أو رقم الهاتف',
      'email_phone_error': 'يرجى إدخال بريدك الإلكتروني أو رقم الهاتف',
      'email_phone_invalid': 'يرجى إدخال بريد إلكتروني أو رقم هاتف صحيح',
      'password_label': 'كلمة المرور',
      'password_hint': 'أدخل كلمة المرور',
      'password_error': 'يرجى إدخال كلمة المرور',
      'remember_me': 'تذكرني',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login_button': 'تسجيل الدخول',
      'or_continue_with': 'أو المتابعة باستخدام',
      'no_account': 'ليس لديك حساب؟ ',
      'sign_up': 'إنشاء حساب',
      'login_success': 'تم تسجيل الدخول بنجاح!',
      'login_failed': 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
      'sign_up_google': 'تسجيل الدخول باستخدام Google',
      'sign_up_apple': 'تسجيل الدخول باستخدام Apple',
      'sign_up_facebook': 'تسجيل الدخول باستخدام Facebook',
      'forgot_password_title': 'نسيت كلمة المرور ؟',
      'forgot_password_subtitle': 'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.',
      'forgot_password_email_hint': 'أدخل بريدك الإلكتروني',
      'send_reset_link': 'إرسال رابط إعادة تعيين كلمة المرور',
      'back_to_login': 'العودة إلى تسجيل الدخول',
      'google_login_todo': 'تسجيل الدخول بجوجل - سيتم تنفيذه مع google_sign_in package',
      'apple_login_todo': 'تسجيل الدخول بآبل - سيتم تنفيذه مع sign_in_with_apple package',
      'facebook_login_todo': 'تسجيل الدخول بفيسبوك - سيتم تنفيذه مع flutter_facebook_auth package',
      'email_label': 'البريد الإلكتروني',
      'reset_link_sent': 'تم إرسال رابط إعادة التعيين!',
      'reset_link_instructions': 'يرجى التحقق من بريدك الوارد واتباع التعليمات الخاصة برابط إعادة تعيين كلمة المرور.',
      'create_account': 'إنشاء حساب',
      'full_name_label': 'الاسم الكامل',
      'full_name_hint': 'أدخل اسمك الكامل',
      'confirm_password_label': 'تأكيد كلمة المرور',
      'confirm_password_hint': 'تأكيد كلمة المرور الخاصة بك',
      'travel_preferences_title': 'تفضيلات السفر',
      'duration_question': 'كم من الوقت تخطط للسفر؟',
      'duration_question_title': 'مدة السفر',
      'budget_question': 'ما هو ميزانيتك التقريبية؟',
      'budget_question_title': 'تفضيل الميزانية',
      'activities_question': 'ما أنواع الأنشطة التي تهمك؟',
      'activities_question_title': 'تفضيلات الأنشطة',
      'accommodation_question': 'ما نوع الإقامة التي تفضلها؟',
      'accommodation_question_title': 'نوع الإقامة',
      'group_size_question': 'من تسافر معهم؟',
      'group_size_question_title': 'حجم المجموعة',
      'transportation_question_title': 'تفضيل النقل',
      'multiple_choice_instruction': 'اختر جميع الخيارات التي تهمك',
      'Next': 'التالي',
      'finish': 'إنهاء',
      'skip_button': 'تأجيل لاحقًا',
      'preferences_saved': '✅ تم حفظ التفضيلات بنجاح!',
      'preferences_saved_success': 'تم حفظ التفضيلات بنجاح!',
      'budget_economic': 'اقتصادي (< 500 درهم/يوم)',
      'budget_moderate': 'متوسط (500-1500 درهم/يوم)',
      'budget_luxury': 'فاخر (> 1500 درهم/يوم)',
      'budget_friendly': 'ميزانية منخفضة',
      'activity_culture': 'الثقافة والتاريخ',
      'activity_nature': 'الطبيعة والتسلق',
      'activity_beach': 'الشاطئ والاسترخاء',
      'activity_adventure': 'الرياضة والمغامرة',
      'activity_nightlife': 'الحياة الليلية',
      'activity_gastronomy': 'المأكولات',
      'accommodation_hotel': 'فندق',
      'accommodation_hostel': 'دار شباب',
      'accommodation_airbnb': 'إيربي إن/تأجير',
      'accommodation_camping': 'تخييم',
      'accommodation_luxury_hotel': 'فندق فاخر',
      'accommodation_boutique_hotel': 'فندق بوتيك',
      'accommodation_business_hotel': 'فندق أعمال',
      'accommodation_budget_hotel': 'فندق اقتصادي',
      'accommodation_resort': 'منتجع',
      'accommodation_riad': 'رياض',
      'accommodation_guesthouse': 'بيت ضيافة',
      'accommodation_apartment': 'شقة',
      'accommodation_villa': 'فيلا',
      'group_solo': 'بمفردي',
      'group_couple': 'كزوج',
      'group_family': 'مع العائلة',
      'group_friends': 'مع الأصدقاء',
      'group_family_kids': 'عائلة مع أطفال',
      'group_family_adults': 'عائلة مع بالغين',
      'group_friends_small': 'مجموعة صغيرة من الأصدقاء',
      'group_friends_large': 'مجموعة كبيرة من الأصدقاء',
      'transportation_flight': 'رحلة جوية',
      'transportation_car_rental': 'تأجير سيارة',
      'transportation_private_driver': 'سائق خاص',
      'transportation_public_transport': 'نقل عام',
      'transportation_train': 'قطار',
      'transportation_taxi_ride_share': 'تاكسي/مشاركة الركوب',
      'transportation_bicycle': 'دراجة هوائية',
      'transportation_walking': 'المشي',
      'activity_culture_history': 'الثقافة والتاريخ',
      'activity_nature_wildlife': 'الطبيعة والحياة البرية',
      'activity_beach_water': 'الشاطئ والأنشطة المائية',
      'activity_adventure_sports': 'رياضات المغامرة',
      'activity_nightlife_entertainment': 'الحياة الليلية والترفيه',
      'activity_food_gastronomy': 'الطعام والمأكولات',
      'activity_shopping': 'التسوق',
      'activity_wellness_spa': 'الرفاهية والسبا',
      'duration_unit': 'أيام',
      'home_title': 'الرئيسية',
      'home_welcome': 'أهلاً',
      'home_search_hint': 'ابحث عن وجهات، أنشطة...',
      'home_recommendations_title': 'التوصيات القريبة منك',
      'rec_park_title': 'الحديقة المركزية',
      'rec_park_subtitle': 'حديقة حضرية رائعة تحتوي على بحيرات ومسارات.',
      'rec_museum_title': 'متحف اللوفر',
      'rec_museum_subtitle': 'استكشف مجموعات فنية عالمية الشهرة.',
      'home_trending_title': 'وجهات متصدرة',
      'trending_paris_name': 'باريس',
      'trending_paris_subtitle': 'مدينة النور تنتظرك.',
      'trending_kyoto_name': 'كيوتو',
      'trending_kyoto_subtitle': 'اكتشف المعابد والحدائق القديمة.',
      'home_seasonal_title': 'نقاط بارزة موسمية',
      'seasonal_summer_title': 'ملاذات الصيف',
      'seasonal_summer_subtitle': 'أماكن مثالية للشمس والبحر.',
      'seasonal_autumn_title': 'مغامرات الخريف',
      'seasonal_autumn_subtitle': 'استكشف أوراق الخريف والطقس البارد.',
      'home_featured_cities_title': 'مدن مميزة',
      'city_nyc_name': 'نيويورك',
      'city_paris_name': 'باريس',
      'city_tokyo_name': 'طوكيو',
      'tag_business': 'أعمال',
      'tag_art_culture': 'فن وثقافة',
      'tag_museums': 'متاحف',
      'tag_cultural_attractions': 'معالم ثقافية',
      'tag_technology': 'تكنولوجيا',
      'tag_traditional_culture': 'ثقافة تقليدية',
      'reviews_label': 'تقييمات',
      'nav_home': 'الرئيسية',
      'nav_explore': 'استكشاف',
      'nav_products': 'المنتجات',
      'nav_saved': 'تم الحفظ',
      'nav_profile': 'الملف الشخصي',
      'explore_title': 'استكشف المغرب',
      'explore_subtitle': 'اكتشف وجهات وأنشطة مذهلة',
      'products_title': 'المنتجات المغربية',
      'products_subtitle': 'تسوق منتجات يدوية أصيلة',
      'saved_title': 'عناصرك المحفوظة',
      'saved_subtitle': 'الأماكن والأنشطة والمنتجات التي حافظت عليها',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'إدارة ملفك الشخصي وتفضيلاتك',
      'of': 'من',
      'guest_mode_info': 'الوضع الضيف - ميزات محدودة',
      'guest_mode_description': 'يمكنك استكشاف التطبيق، لكن بعض الميزات تتطلب تسجيل الدخول',
      'login_required': 'تسجيل الدخول مطلوب',
      'login_required_message': 'هذه الميزة تتطلب تسجيل الدخول. هل تريد تسجيل الدخول الآن؟',
      'cancel': 'إلغاء',
      'login': 'تسجيل الدخول',
    },
    'Español': {
      'skip': 'Saltar',
      'welcome_title': 'Bienvenido a nuestra App',
      'welcome_subtitle': 'Descubre una nueva forma de conectar y explorar.\n¡Comienza tu viaje hoy!',
      'select_language': 'Seleccionar idioma',
      'get_started': 'Empezar',
      'already_account': '¿Ya tienes una cuenta? ',
      'log_in': 'Iniciar sesión',
      'morocco': 'Marruecos',
      'login_title': 'Iniciar sesión',
      'login_subtitle': '¡Bienvenido de vuelta! Por favor, ingresa tus datos.',
      'email_phone_label': 'Email o Teléfono',
      'email_phone_hint': 'Ingresa tu email o teléfono',
      'email_phone_error': 'Por favor ingresa tu email o teléfono',
      'email_phone_invalid': 'Por favor ingresa un email o número de teléfono válido',
      'password_label': 'Contraseña',
      'password_hint': 'Ingresa tu contraseña',
      'password_error': 'Por favor ingresa tu contraseña',
      'remember_me': 'Recordarme',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'login_button': 'Iniciar sesión',
      'or_continue_with': 'O continúa con',
      'no_account': '¿No tienes una cuenta? ',
      'sign_up': 'Registrarse',
      'login_success': '¡Inicio de sesión exitoso!',
      'login_failed': 'Error al iniciar sesión. Por favor, inténtalo de nuevo.',
      'sign_up_google': 'Iniciar sesión con Google',
      'sign_up_apple': 'Iniciar sesión con Apple',
      'sign_up_facebook': 'Iniciar sesión con Facebook',
      'forgot_password_title': '¿Contraseña olvidada?',
      'forgot_password_subtitle': 'Ingresa tu correo electrónico para recibir un enlace de restablecimiento.',
      'forgot_password_email_hint': 'Ingresa tu correo electrónico',
      'send_reset_link': 'Enviar enlace de restablecimiento',
      'back_to_login': 'Volver al inicio de sesión',
      'google_login_todo': 'Login Google - A implementar con google_sign_in package',
      'apple_login_todo': 'Login Apple - A implementar con sign_in_with_apple package',
      'facebook_login_todo': 'Login Facebook - A implementar con flutter_facebook_auth package',
      'email_label': 'Correo electrónico',
      'reset_link_sent': '¡Enlace de restablecimiento enviado!',
      'reset_link_instructions': 'Por favor revisa tu bandeja de entrada y sigue las instrucciones del enlace de restablecimiento de contraseña.',
      'create_account': 'Crear cuenta',
      'full_name_label': 'Nombre completo',
      'full_name_hint': 'Ingresa tu nombre completo',
      'confirm_password_label': 'Confirmar contraseña',
      'confirm_password_hint': 'Confirma tu contraseña',
      'travel_preferences_title': 'Preferencias de viaje',
      'duration_question': '¿Cuánto tiempo planeas viajar?',
      'duration_question_title': 'Duración del viaje',
      'budget_question': '¿Cuál es tu presupuesto aproximado?',
      'budget_question_title': 'Preferencia de presupuesto',
      'activities_question': '¿Qué tipos de actividades te interesan?',
      'activities_question_title': 'Preferencias de actividades',
      'accommodation_question': '¿Qué tipo de alojamiento prefieres?',
      'accommodation_question_title': 'Tipo de alojamiento',
      'group_size_question': '¿Con quién viajas?',
      'group_size_question_title': 'Tamaño del grupo',
      'transportation_question_title': 'Preferencia de transporte',
      'multiple_choice_instruction': 'Selecciona todas las opciones que te interesen',
      'Next': 'Siguiente',
      'finish': 'Finalizar',
      'skip_button': 'Omitir para más tarde',
      'preferences_saved': '✅ ¡Preferencias guardadas con éxito!',
      'preferences_saved_success': '¡Preferencias guardadas con éxito!',
      'budget_economic': 'Económico (< 500 DH/día)',
      'budget_moderate': 'Moderado (500-1500 DH/día)',
      'budget_luxury': 'Lujoso (> 1500 DH/día)',
      'budget_friendly': 'Económico',
      'activity_culture': 'Cultura e Historia',
      'activity_nature': 'Naturaleza y Senderismo',
      'activity_beach': 'Playa y Relajación',
      'activity_adventure': 'Deportes y Aventura',
      'activity_nightlife': 'Vida nocturna',
      'activity_gastronomy': 'Gastronomía',
      'accommodation_hotel': 'Hotel',
      'accommodation_hostel': 'Albergue juvenil',
      'accommodation_airbnb': 'Airbnb/Alquiler',
      'accommodation_camping': 'Camping',
      'accommodation_luxury_hotel': 'Hotel de lujo',
      'accommodation_boutique_hotel': 'Hotel boutique',
      'accommodation_business_hotel': 'Hotel de negocios',
      'accommodation_budget_hotel': 'Hotel económico',
      'accommodation_resort': 'Resort',
      'accommodation_riad': 'Riad',
      'accommodation_guesthouse': 'Casa de huéspedes',
      'accommodation_apartment': 'Apartamento',
      'accommodation_villa': 'Villa',
      'group_solo': 'Solo',
      'group_couple': 'En pareja',
      'group_family': 'Con familia',
      'group_friends': 'Con amigos',
      'group_family_kids': 'Familia con niños',
      'group_family_adults': 'Familia con adultos',
      'group_friends_small': 'Pequeño grupo de amigos',
      'group_friends_large': 'Gran grupo de amigos',
      'transportation_flight': 'Vuelo',
      'transportation_car_rental': 'Alquiler de coche',
      'transportation_private_driver': 'Conductor privado',
      'transportation_public_transport': 'Transporte público',
      'transportation_train': 'Tren',
      'transportation_taxi_ride_share': 'Taxi/Compartir viaje',
      'transportation_bicycle': 'Bicicleta',
      'transportation_walking': 'Caminar',
      'activity_culture_history': 'Cultura e Historia',
      'activity_nature_wildlife': 'Naturaleza y Vida Silvestre',
      'activity_beach_water': 'Playa y Actividades Acuáticas',
      'activity_adventure_sports': 'Deportes de Aventura',
      'activity_nightlife_entertainment': 'Vida Nocturna y Entretenimiento',
      'activity_food_gastronomy': 'Comida y Gastronomía',
      'activity_shopping': 'Compras',
      'activity_wellness_spa': 'Bienestar y Spa',
      'duration_unit': 'días',
      'home_title': 'Inicio',
      'home_welcome': 'Bienvenido',
      'home_search_hint': 'Buscar destinos, actividades...',
      'home_recommendations_title': 'Recomendaciones cerca de ti',
      'rec_park_title': 'Parque Central',
      'rec_park_subtitle': 'Un hermoso parque urbano con lagos y senderos.',
      'rec_museum_title': 'Museo del Louvre',
      'rec_museum_subtitle': 'Explora colecciones de arte famosas en el mundo.',
      'home_trending_title': 'Destinos en tendencia',
      'trending_paris_name': 'París',
      'trending_paris_subtitle': 'La Ciudad de la Luz te espera.',
      'trending_kyoto_name': 'Kioto',
      'trending_kyoto_subtitle': 'Descubre templos y jardines antiguos.',
      'home_seasonal_title': 'Destacados estacionales',
      'seasonal_summer_title': 'Escapadas de verano',
      'seasonal_summer_subtitle': 'Lugares perfectos para el sol y el mar.',
      'seasonal_autumn_title': 'Aventuras de otoño',
      'seasonal_autumn_subtitle': 'Explora el follaje de otoño y el clima fresco.',
      'home_featured_cities_title': 'Ciudades destacadas',
      'city_nyc_name': 'Nueva York',
      'city_paris_name': 'París',
      'city_tokyo_name': 'Tokio',
      'tag_business': 'Negocios',
      'tag_art_culture': 'Arte y Cultura',
      'tag_museums': 'Museos',
      'tag_cultural_attractions': 'Atracciones culturales',
      'tag_technology': 'Tecnología',
      'tag_traditional_culture': 'Cultura tradicional',
      'reviews_label': 'reseñas',
      'nav_home': 'Inicio',
      'nav_explore': 'Explorar',
      'nav_products': 'Productos',
      'nav_saved': 'Guardado',
      'nav_profile': 'Perfil',
      'explore_title': 'Explora Marruecos',
      'explore_subtitle': 'Descubre destinos y actividades increíbles',
      'products_title': 'Productos Marroquíes',
      'products_subtitle': 'Compra productos artesanales auténticos',
      'saved_title': 'Tus Elementos Guardados',
      'saved_subtitle': 'Lugares, actividades y productos que guardaste',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'Administra tu perfil y preferencias',
      'of': 'de', // Added for progress indicator
      'guest_mode_info': 'Modo invitado - Funciones limitadas',
      'guest_mode_description': 'Puedes explorar la aplicación, pero algunas funciones requieren inicio de sesión',
      'login_required': 'Inicio de sesión requerido',
      'login_required_message': 'Esta función requiere inicio de sesión. ¿Te gustaría iniciar sesión ahora?',
      'cancel': 'Cancelar',
      'login': 'Iniciar sesión',
    },
  };
}