import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../constants/constants.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _currentLanguage = 'English';
  String get currentLanguage => _currentLanguage;

  // Getter pour obtenir la liste des langues disponibles
  List<String> get availableLanguages => _translations.keys.toList();

  // Méthode pour vérifier si une langue est disponible
  bool isLanguageSupported(String language) {
    return _translations.containsKey(language);
  }

  // Méthode pour initialiser la langue depuis les préférences
  Future<void> initializeLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLanguage = prefs.getString(AppConstants.languageKey);
      if (savedLanguage != null && isLanguageSupported(savedLanguage)) {
        _currentLanguage = savedLanguage;
        notifyListeners();
      }
    } catch (e) {
      debugPrint('Error loading saved language: $e');
    }
  }

  Future<void> changeLanguage(String language) async {
    if (isLanguageSupported(language)) {
      _currentLanguage = language;

      // Sauvegarder la langue dans les préférences
      try {
        final prefs = await SharedPreferences.getInstance();
        await prefs.setString(AppConstants.languageKey, language);
      } catch (e) {
        debugPrint('Error saving language preference: $e');
      }

      notifyListeners();
    } else {
      debugPrint(
        'Warning: Language "$language" is not supported. Using current language: $_currentLanguage',
      );
    }
  }

  String translate(String key) {
    final languageMap = _translations[_currentLanguage];
    if (languageMap == null) {
      debugPrint(
        'Warning: No translations found for language: $_currentLanguage',
      );
      return key;
    }
    return languageMap[key] ?? key;
  }

  // Méthode utilitaire pour obtenir la direction du texte
  TextDirection get textDirection {
    return _currentLanguage == 'العربية'
        ? TextDirection.rtl
        : TextDirection.ltr;
  }

  // Méthode pour obtenir le code de langue (utile pour les APIs)
  String get languageCode {
    switch (_currentLanguage) {
      case 'English':
        return 'en';
      case 'Français':
        return 'fr';
      case 'العربية':
        return 'ar';
      case 'Español':
        return 'es';
      default:
        return 'en';
    }
  }

  // Méthode pour obtenir le nom natif de la langue
  String get nativeLanguageName {
    switch (_currentLanguage) {
      case 'English':
        return 'English';
      case 'Français':
        return 'Français';
      case 'العربية':
        return 'العربية';
      case 'Español':
        return 'Español';
      default:
        return 'English';
    }
  }

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'skip': 'Skip',
      'welcome_title': 'Welcome To Morocco',
      'welcome_subtitle':
          'Discover a new way to connect and explore.\nGet started on your journey today!',
      'select_language': 'Select Language',
      'get_started': 'Get Started',
      'already_account': 'Already have an account? ',
      'log_in': 'Log In',
      'morocco': 'Morocco',
      'login_title': 'Log In',
      'login_subtitle': 'Welcome back! Please enter your details.',
      'email_phone_label': 'Email or Phone',
      'email_phone_hint': 'Enter your email or phone',
      'email_phone_error': 'Please enter your email or phone',
      'email_phone_invalid': 'Please enter a valid email or phone number',
      'username_email_label': 'Username or Email',
      'username_email_hint': 'Enter your username or email',
      'username_email_error': 'Please enter your username or email',
      'username_email_invalid': 'Please enter a valid username or email',
      'password_label': 'Password',
      'password_hint': 'Enter your password',
      'password_error': 'Please enter your password',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot Password?',
      'login_button': 'Log In',
      'or_continue_with': 'Or continue with',
      'no_account': "Don't have an account? ",
      'sign_up': 'Sign Up',
      'login_success': 'Login successful!',
      'login_failed': 'Login failed. Please try again.',
      'sign_up_google': 'Sign up with Google',
      'sign_up_apple': 'Sign up with Apple',
      'sign_up_facebook': 'Sign up with Facebook',
      'forgot_password_title': 'Forgotten Password ?',
      'forgot_password_subtitle':
          'Enter your email address to receive a password reset link.',
      'forgot_password_email_hint': 'Enter your email address',
      'send_reset_link': 'Send password reset link',
      'back_to_login': 'Back to login',
      'google_login_todo':
          'Google Login - To be implemented with google_sign_in package',
      'apple_login_todo':
          'Apple Login - To be implemented with sign_in_with_apple package',
      'facebook_login_todo':
          'Facebook Login - To be implemented with flutter_facebook_auth package',
      'email_label': 'Email',
      'reset_link_sent': 'Reset link sent!',
      'reset_link_instructions':
          'Please check your inbox mail and follow the instructions for the password reset link.',
      'create_account': 'Create Account',
      'full_name_label': 'Full Name',
      'full_name_hint': 'Enter your full name',
      'confirm_password_label': 'Confirm Password',
      'confirm_password_hint': 'Confirm your password',
      'travel_preferences_title': 'Travel Preferences',
      'duration_question': 'How long do you plan to travel ?',
      'duration_question_title': 'Travel Duration',
      'budget_question': 'What is your approximate budget ?',
      'budget_question_title': 'Budget Preference',
      'activities_question': 'What types of activities interest you ?',
      'activities_question_title': 'Activity Preferences',
      'accommodation_question': 'What type of accommodation do you prefer ?',
      'accommodation_question_title': 'Accommodation Type',
      'group_size_question': 'Who are you traveling with ?',
      'group_size_question_title': 'Group Size',
      'transportation_question_title': 'Transportation Preference',
      'multiple_choice_instruction': 'Select all the options that interest you',
      'Next': 'Next',
      'finish': 'Finish',
      'skip_button': 'Skip for later',
      'preferences_saved': '✅ Preferences saved successfully!',
      'preferences_saved_success': 'Preferences saved successfully!',
      'welcome_preferences_title': 'Personalize your experience',
      'welcome_preferences_subtitle':
          'Help us recommend the best destinations for you',
      'previous': 'Previous',
      'next': 'Next',
      'budget_economic': 'Economic (< 500 DH/day)',
      'budget_moderate': 'Moderate (500-1500 DH/day)',
      'budget_luxury': 'Luxurious (> 1500 DH/day)',
      'budget_friendly': 'Budget Friendly',
      'activity_culture': 'Culture & History',
      'activity_nature': 'Nature & Hiking',
      'activity_beach': 'Beach & Relaxation',
      'activity_adventure': 'Sports & Adventure',
      'activity_nightlife': 'Nightlife',
      'activity_gastronomy': 'Gastronomy',
      'accommodation_hotel': 'Hotel',
      'accommodation_hostel': 'Youth hostel',
      'accommodation_airbnb': 'Airbnb/Rental',
      'accommodation_camping': 'Camping',
      'accommodation_luxury_hotel': 'Luxury Hotel',
      'accommodation_boutique_hotel': 'Boutique Hotel',
      'accommodation_business_hotel': 'Business Hotel',
      'accommodation_budget_hotel': 'Budget Hotel',
      'accommodation_resort': 'Resort',
      'accommodation_riad': 'Riad',
      'accommodation_guesthouse': 'Guesthouse',
      'accommodation_apartment': 'Apartment',
      'accommodation_villa': 'Villa',
      'group_solo': 'Alone',
      'group_couple': 'As a couple',
      'group_family': 'With family',
      'group_friends': 'With friends',
      'group_family_kids': 'Family with Kids',
      'group_family_adults': 'Family with Adults',
      'group_friends_small': 'Small Group of Friends',
      'group_friends_large': 'Large Group of Friends',
      'transportation_flight': 'Flight',
      'transportation_car_rental': 'Car Rental',
      'transportation_private_driver': 'Private Driver',
      'transportation_public_transport': 'Public Transport',
      'transportation_train': 'Train',
      'transportation_taxi_ride_share': 'Taxi/Ride Share',
      'transportation_bicycle': 'Bicycle',
      'transportation_walking': 'Walking',
      'activity_culture_history': 'Culture & History',
      'activity_nature_wildlife': 'Nature & Wildlife',
      'activity_beach_water': 'Beach & Water Activities',
      'activity_adventure_sports': 'Adventure Sports',
      'activity_nightlife_entertainment': 'Nightlife & Entertainment',
      'activity_food_gastronomy': 'Food & Gastronomy',
      'activity_shopping': 'Shopping',
      'activity_wellness_spa': 'Wellness & Spa',
      'duration_unit': 'days',
      'home_title': 'Home',
      'home_welcome': 'Welcome',
      'guest_ready_to_travel': 'Ready to start your journey?',
      'guest_create_account_description':
          'Create your account to save your preferences and access all features',
      'guest_login': 'Log In',
      'guest_signup': 'Sign Up',
      'guest_unlock_features': 'Unlock all features',
      'guest_edit_profile': 'Edit your profile and preferences',
      'guest_manage_reservations': 'Manage your reservations',
      'guest_save_destinations': 'Save your favorite destinations',
      'guest_write_reviews': 'Leave reviews and comments',
      'guest_share_photos': 'Share your travel photos',
      'home_search_hint': 'Search destinations, activities...',
      'home_recommendations_title': 'Recommendations Near You',
      'rec_park_title': 'Central Park',
      'rec_park_subtitle': 'A beautiful urban park with lakes and trails.',
      'rec_museum_title': 'Louvre Museum',
      'rec_museum_subtitle': 'Explore world-famous art collections.',
      'home_trending_title': 'Trending Destinations',
      'trending_paris_name': 'Paris',
      'trending_paris_subtitle': 'The City of Light awaits you.',
      'trending_kyoto_name': 'Kyoto',
      'trending_kyoto_subtitle': 'Discover ancient temples and gardens.',
      'home_seasonal_title': 'Seasonal Highlights',
      'seasonal_summer_title': 'Summer Escapes',
      'seasonal_summer_subtitle': 'Perfect spots for sun and sea.',
      'seasonal_autumn_title': 'Autumn Adventures',
      'seasonal_autumn_subtitle': 'Explore fall foliage and cool weather.',
      'home_featured_cities_title': 'Featured Cities',
      'city_nyc_name': 'New York City',
      'city_paris_name': 'Paris',
      'city_tokyo_name': 'Tokyo',
      'tag_business': 'Business',
      'tag_art_culture': 'Art & Culture',
      'tag_museums': 'Museums',
      'tag_cultural_attractions': 'Cultural Attractions',
      'tag_technology': 'Technology',
      'tag_traditional_culture': 'Traditional Culture',
      'reviews_label': 'reviews',
      'nav_home': 'Home',
      'nav_explore': 'Explore',
      'nav_products': 'Products',
      'nav_saved': 'Saved',
      'nav_profile': 'Profile',
      'explore_title': 'Explore Morocco',
      'explore_subtitle': 'Discover amazing destinations and activities',
      'products_title': 'Moroccan Products',
      'products_subtitle': 'Shop authentic handmade products',
      'saved_title': 'Your Saved Items',
      'saved_subtitle': 'Places, activities and products you saved',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'Manage your profile and preferences',
      'of': 'of',
      'guest_mode_info': 'Guest mode - Limited features',
      'guest_mode_description':
          'You can explore the app, but some features require login',
      'login_required': 'Login Required',
      'login_required_message':
          'This feature requires login. Would you like to login now?',
      'cancel': 'Cancel',
      'login': 'Login',
      // Trip management translations
      'Trips': 'Trips',
      'create_trip': 'Create Trip',
      'edit_trip': 'Edit Trip',
      'trip_details': 'Trip Details',
      'trip_name': 'Trip Name',
      'trip_name_required': 'Trip name is required',

      'destination_required': 'Destination is required',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'notes': 'Notes',
      'activities': 'Activities',
      'add_activity': 'Add Activity',
      'no_activities_added': 'No activities added yet',
      'add_activities_description':
          'Tap the buttons above to add activities to your trip',
      'save_changes': 'Save Changes',
      'create_your_first_trip':
          'Create your first trip and start planning your adventure',
      'no_trips_saved': 'No trips saved yet',
      'created': 'Created',
      'edit_activity': 'Edit Activity',
      'activity_name': 'Activity Name',
      'description_optional': 'Description (Optional)',
      'location_optional': 'Location (Optional)',
      'duration_minutes': 'Duration in minutes (Optional)',
      'type': 'Type',
      'custom': 'Custom',
      'attraction': 'Attraction',
      'restaurant': 'Restaurant',
      'hotel': 'Hotel',
      'transport': 'Transport',
      'add': 'Add',
      'save': 'Save',
      'delete_trip': 'Delete Trip',
      'delete_trip_confirmation':
          'Are you sure you want to delete this trip? This action cannot be undone.',
      'delete': 'Delete',
      'trip_created_successfully': 'Trip created successfully!',
      'trip_saved_successfully': 'Trip saved successfully!',
      'error_creating_trip': 'Error creating trip',
      'error_saving_trip': 'Error saving trip',
      'please_select_dates': 'Please select start and end dates',
      'start_date_after_end_date': 'Start date must be before end date',
      'please_select_destination': 'Please select a destination first',
      'add_existing_activities': 'Add Existing Activities',
      'add_activities_from': 'Add Activities from',
      'search_activities': 'Search activities...',
      'no_attractions_found': 'No attractions found for this destination',
      'save_selected': 'Save',
      'selected_activities': 'Selected Activities',
      'trip_deleted_successfully': 'Trip deleted successfully',
      'error_deleting_trip': 'Error deleting trip',
      'plan_your_itinerary': 'Plan Your Itinerary',
      'trip_duration': 'Trip Duration',
      'one_day': '1 Day',
      'two_days': '2 Days',
      'three_days': '3 Days',
      'five_days': '5 Days',
      'days': 'days',
      'budget': 'Budget',
      'budget_range': 'Budget Range',
      'low_range': 'Budget',
      'mid_range': 'Mid-Range',
      'high_range': 'Luxury',
      'luxury': 'Luxury',
      'select_date': 'Select Date',
      'activities_interests': 'Activities & Interests',
      'select_activities': 'Select activities you\'d like to include',
      'generate_itinerary': 'Generate Itinerary',
      'itinerary_generated': 'Itinerary Generated!',
      'itinerary_success':
          'Your personalized itinerary has been created successfully.',
      'ok': 'OK',
      'share': 'Share',
      'activity_booked_title': 'Activity Booked!',
      'activity_booked_success': 'You have successfully booked:',
      'season': 'Season',
      'all_year': 'All year',
      'share_functionality_coming_soon': 'Share functionality coming soon!',
      'route_not_found': 'Route not found',
      'search_title': 'Search',
      'search_page_title': 'Search Page',
      'coming_soon': 'Coming soon...',

      'destination_detail': 'Destination Detail',
      'detail_page_coming_soon': 'Detail page coming soon...',

      'activity_detail': 'Activity Detail',

      'product_detail': 'Product Detail',
      'collection': 'Collection',
      'seasonal_collection': 'Seasonal Collection',
      'collection_page_coming_soon': 'Collection page coming soon...',
      'settings': 'Settings',
      'settings_page_coming_soon': 'Settings page coming soon...',
      'help_support': 'Help & Support',
      'help_page_coming_soon': 'Help page coming soon...',
      'error_skipping_questionnaire': 'Error while skipping the questionnaire',
      'error_saving_preferences': 'Error while saving preferences',
      'retry': 'Retry',
      'book_now': 'Book Now',
      'added_to_wishlist': 'Added to wishlist',
      'removed_from_wishlist': 'Removed from wishlist',
      'view_details': 'View Details',
      'error_booking_activity': 'Error booking activity',
      'city_label_colon': 'City:',
      'loading_cities': 'Loading cities...',
      'all_cities': 'All cities',
      'get_directions': 'Get Directions',
      'directions_functionality_coming_soon': 'Directions functionality coming soon!',
      'phone_hint_example': '+212 6XX XX XX XX',
      'search_cities_countries_activities_hint': 'Search cities, countries, or activities...',
      'otp_hint': '------',
      'activity_sightseeing': 'Sightseeing',
      'activity_food_tour': 'Food Tour',
      'activity_cultural_visit': 'Cultural Visit',
      'activity_relaxation': 'Relaxation',
      'unknown_destination': 'Unknown Destination',
      // Filter page translations
      'filters': 'Filters',
      'clear': 'Clear',
      'category': 'Category',
      'all': 'All',
      'cities': 'Cities',
      'culture': 'Culture',
      'nature': 'Nature',
      'adventure': 'Adventure',
      'beach': 'Beach',
      'desert': 'Desert',
      'all_budgets': 'All Budgets',
      'duration': 'Duration',
      'any_duration': 'Any Duration',
      'weekend': 'Weekend',
      'short_trip': 'Short Trip',
      'one_week': 'One Week',
      'extended': 'Extended',
      'experience_type': 'Experience Type',
      'apply_filters': 'Apply Filters',
      // Profile page translations
      'profile': 'Profile',
      'member_since': 'Member since',
      'contribution': 'contribution',
      'contributions': 'contributions',
      'tell_about_yourself': 'Tell other travelers a bit about yourself.',
      'no_city_selected': 'No city selected.',
      'your_achievements': 'Your Achievements',
      'show_all': 'Show all',
      'write_first_review': 'Write your first review',
      'unlock_levels_reviews': 'Unlock levels with reviews',
      'upload_first_photo': 'Upload your first photo',
      'unlock_levels_photos': 'Unlock levels with photos',
      'reservations': 'Reservations',
      'preferences': 'Preferences',
      'theme': 'Theme',
      'choose_theme': 'Choose Theme',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'always_use_light': 'Always use light theme',
      'always_use_dark': 'Always use dark theme',
      'follow_system_theme': 'Follow system theme',
      // Edit Profile page translations
      'account_information': 'Account Information',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'enter_first_name': 'Enter your first name',
      'enter_last_name': 'Enter your last name',
      'home_airport': 'Home Airport',
      'airport_hint': 'Enter your home airport code',
      'enter_email': 'Enter your email address',
      'full_address': 'Full Address',
      'enter_address': 'Enter your full address',
      'address_suite': 'Address/Suite',
      'additional_address_info': 'Additional address information',
      'city': 'City',
      'enter_city': 'Enter your city',
      'state_region_province': 'State/Region/Province',
      'enter_region': 'Enter your region',
      'postal_code': 'Postal Code',
      'enter_postal_code': 'Enter your postal code',
      'country': 'Country',
      'select_country': 'Select your country',
      'france': 'France',
      'spain': 'Spain',
      'usa': 'USA',
      'phone_number': 'Phone Number',
      'renew_password': 'Renew Password',
      'profile_updated_success': 'Profile updated successfully!',
      'field_required': 'This field is required',
      'choose_from_gallery': 'Choose from Gallery',
      'take_photo': 'Take Photo',
      // Wishlist/Saved page translations
      'wishlist': 'Wishlist',
      'products': 'Products',
      'no_activities_saved': 'No activities saved yet',
      'start_exploring_activities':
          'Start exploring and save your favorite activities',
      'explore_activities': 'Explore Activities',
      'no_cities_saved': 'No cities saved yet',
      'save_cities_visit': 'Save cities you want to visit',
      'explore_cities': 'Explore Cities',
      'no_products_saved': 'No products saved yet',
      'save_products_buy': 'Save products you want to buy',
      'explore_products': 'Explore Products',
      'activity': 'Activity',
      'location': 'Location',
      'price': 'Price',
      // Explore page translations
      'explore_morocco': 'Explore Morocco',
      'search_cities_activities': 'Search cities, activities...',
      'categories': 'Categories',
      'popular_cities': 'Popular Cities',
      'recommended_activities': 'Recommended Activities',
      'upcoming_events': 'Upcoming Events',
      'view_all': 'View All',
      'marrakech': 'Marrakech',
      'fes': 'Fes',
      'chefchaouen': 'Chefchaouen',
      'sahara_desert_safari': 'Sahara Desert Safari',
      'marrakech_medina_tour': 'Marrakech Medina Tour',
      'moroccan_cooking_class': 'Moroccan Cooking Class',
      'cinema_world_music_festival': 'Cinema World Music Festival',
      'rose_festival': 'Rose Festival',
      'essaouira': 'Essaouira',
      'kelaat_mgouna': 'Kelaat M\'Gouna',
      'june_10_15': 'June 10-15',
      'may_10_12': 'May 10-12',
      // Products page translations
      '2_4_hours': '2-4 hours',
      '3_4_hours': '3-4 hours',
      '2_3_hours': '2-3 hours',
      '1_2_hours': '1-2 hours',
      '4_6_hours': '4-6 hours',
      // Search page translations
      'search_morocco': 'Search Morocco',
      'search_cities_activities_hint': 'Search cities, activities...',
      'search_for_cities_activities':
          'Search for cities, activities, or attractions',
      'no_results_found': 'No results found for',
      'try_different_keywords': 'Try different keywords or check spelling',
      // Details page translations
      'key_attractions': 'Key Attractions',
      'location_on_map': 'Location on Map',
      'map_view': 'Map View',
      'explore_the_souks': 'Explore the Souks',
      'visit_secret_garden': 'Visit the Secret Garden',
      'enjoy_traditional_hammam': 'Enjoy a traditional Hammam',
      'hot_air_balloon_ride': 'Hot Air Balloon Ride',
      'various_locations': 'Various locations',
      'medina': 'Medina',
      'palmerale': 'Palmerale',
      // Enhanced Welcome Screen translations
      'choose_your_city': 'Choose your city',
      'detecting_location': 'Detecting your location...',
      'selected_city_info': 'City Information',
      // Reservations page translations
      'no_reservations_yet': 'No reservations yet? Let\'s fix that!',
      'book_before_you_go': 'Book before you go to discover the best on site.',
      'start_planning': 'Start planning',
      'new_trip': 'New Trip',
      'explore': 'Explore',
      'logout': 'Logout',
      // Cart & Checkout
      'shopping_cart': 'Shopping Cart',
      'failed_load_cart_items': 'Failed to load cart items',
      'cart_empty_title': 'Your cart is empty',
      'cart_empty_subtitle': 'Add some products to get started!',
      'continue_shopping': 'Continue Shopping',
      'total': 'Total:',
      'proceed_to_checkout': 'Proceed to Checkout',
      'checkout': 'Checkout',
      'place_order': 'Place Order',
      'order_summary': 'Order Summary',
      'qty': 'Qty',
      'shipping_information': 'Shipping Information',
      'enter_full_name': 'Please enter your full name',
      'enter_valid_email': 'Please enter a valid email address',
      'enter_phone_number': 'Please enter your phone number',
      'credit_card': 'Credit Card',
      'pay_with_credit_card': 'Pay with your credit card',
      'pay_with_paypal': 'Pay with your PayPal account',
      'cash_on_delivery': 'Cash on Delivery',
      'pay_on_delivery': 'Pay when your order arrives',
    },
    'Français': {
      'skip': 'Passer',
      'welcome_title': 'Bienvenue au Maroc',
      'welcome_subtitle':
          'Découvrez une nouvelle façon de vous connecter et d\'explorer.\nCommencez votre voyage aujourd\'hui!',
      'select_language': 'Sélectionner la langue',
      'get_started': 'Commencer',
      'already_account': 'Vous avez déjà un compte? ',
      'log_in': 'Se connecter',
      'morocco': 'Maroc',
      'login_title': 'Se connecter',
      'login_subtitle': 'Bon retour! Veuillez entrer vos détails.',
      'email_phone_label': 'Email ou Téléphone',
      'email_phone_hint': 'Entrez votre email ou téléphone',
      'email_phone_error': 'Veuillez entrer votre email ou téléphone',
      'email_phone_invalid':
          'Veuillez entrer un email ou numéro de téléphone valide',
      'username_email_label': 'Nom d\'utilisateur ou Email',
      'username_email_hint': 'Entrez votre nom d\'utilisateur ou email',
      'username_email_error':
          'Veuillez entrer votre nom d\'utilisateur ou email',
      'username_email_invalid':
          'Veuillez entrer un nom d\'utilisateur ou email valide',
      'password_label': 'Mot de passe',
      'password_hint': 'Entrez votre mot de passe',
      'password_error': 'Veuillez entrer votre mot de passe',
      'remember_me': 'Se souvenir de moi',
      'forgot_password': 'Mot de passe oublié?',
      'login_button': 'Se connecter',
      'or_continue_with': 'Ou continuer avec',
      'no_account': 'Vous n\'avez pas de compte? ',
      'sign_up': 'S\'inscrire',
      'login_success': 'Connexion réussie!',
      'login_failed': 'Échec de la connexion. Veuillez réessayer.',
      'sign_up_google': 'Se connecter avec Google',
      'sign_up_apple': 'Se connecter avec Apple',
      'sign_up_facebook': 'Se connecter avec Facebook',
      'forgot_password_title': 'Mot de passe oublié ?',
      'forgot_password_subtitle':
          'Entrez votre adresse email pour recevoir un lien de réinitialisation.',
      'forgot_password_email_hint': 'Entrez votre adresse email',
      'send_reset_link': 'Envoyer le lien de réinitialisation',
      'back_to_login': 'Retour à la connexion',
      'google_login_todo':
          'Connexion Google - À implémenter avec google_sign_in package',
      'apple_login_todo':
          'Connexion Apple - À implémenter avec sign_in_with_apple package',
      'facebook_login_todo':
          'Connexion Facebook - À implémenter avec flutter_facebook_auth package',
      'email_label': 'Email',
      'reset_link_sent': 'Lien de réinitialisation envoyé !',
      'reset_link_instructions':
          'Veuillez vérifier votre boîte de réception et suivre les instructions du lien de réinitialisation du mot de passe.',
      'create_account': 'Créer un compte',
      'full_name_label': 'Nom complet',
      'full_name_hint': 'Entrez votre nom complet',
      'confirm_password_label': 'Confirmer le mot de passe',
      'confirm_password_hint': 'Confirmez votre mot de passe',
      'travel_preferences_title': 'Préférences de voyage',
      'duration_question': 'Combien de temps prévoyez-vous de voyager ?',
      'duration_question_title': 'Durée du voyage',
      'budget_question': 'Quel est votre budget approximatif ?',
      'budget_question_title': 'Préférence de budget',
      'activities_question': 'Quels types d\'activités vous intéressent ?',
      'activities_question_title': 'Préférences d\'activités',
      'accommodation_question': 'Quel type d\'hébergement préférez-vous ?',
      'accommodation_question_title': 'Type d\'hébergement',
      'group_size_question': 'Avec qui voyagez-vous ?',
      'group_size_question_title': 'Taille du groupe',
      'transportation_question_title': 'Préférence de transport',
      'multiple_choice_instruction':
          'Sélectionnez toutes les options qui vous intéressent',
      'Next': 'Suivant',
      'finish': 'Terminer',
      'skip_button': 'Passer pour plus tard',
      'preferences_saved': '✅ Préférences enregistrées avec succès !',
      'preferences_saved_success': 'Préférences enregistrées avec succès !',
      'welcome_preferences_title': 'Personnalisez votre expérience',
      'welcome_preferences_subtitle':
          'Aidez-nous à vous recommander les meilleures destinations',
      'previous': 'Précédent',
      'next': 'Suivant',

      'budget_economic': 'Économique (< 500 DH/jour)',
      'budget_moderate': 'Modéré (500-1500 DH/jour)',
      'budget_luxury': 'Luxueux (> 1500 DH/jour)',
      'budget_friendly': 'Économique',
      'activity_culture': 'Culture & Histoire',
      'activity_nature': 'Nature & Randonnée',
      'activity_beach': 'Plage & Détente',
      'activity_adventure': 'Sports & Aventure',
      'activity_nightlife': 'Vie nocturne',
      'activity_gastronomy': 'Gastronomie',
      'accommodation_hotel': 'Hôtel',
      'accommodation_hostel': 'Auberge de jeunesse',
      'accommodation_airbnb': 'Airbnb/Location',
      'accommodation_camping': 'Camping',
      'accommodation_luxury_hotel': 'Hôtel de luxe',
      'accommodation_boutique_hotel': 'Hôtel boutique',
      'accommodation_business_hotel': 'Hôtel d\'affaires',
      'accommodation_budget_hotel': 'Hôtel économique',
      'accommodation_resort': 'Station balnéaire',
      'accommodation_riad': 'Riad',
      'accommodation_guesthouse': 'Maison d\'hôtes',
      'accommodation_apartment': 'Appartement',
      'accommodation_villa': 'Villa',
      'group_solo': 'Seul',
      'group_couple': 'En couple',
      'group_family': 'Avec la famille',
      'group_friends': 'Avec des amis',
      'group_family_kids': 'Famille avec enfants',
      'group_family_adults': 'Famille avec adultes',
      'group_friends_small': 'Petit groupe d\'amis',
      'group_friends_large': 'Grand groupe d\'amis',
      'transportation_flight': 'Vol',
      'transportation_car_rental': 'Location de voiture',
      'transportation_private_driver': 'Chauffeur privé',
      'transportation_public_transport': 'Transport public',
      'transportation_train': 'Train',
      'transportation_taxi_ride_share': 'Taxi/Partage de trajet',
      'transportation_bicycle': 'Vélo',
      'transportation_walking': 'Marche',
      'activity_culture_history': 'Culture & Histoire',
      'activity_nature_wildlife': 'Nature & Faune',
      'activity_beach_water': 'Plage & Activités aquatiques',
      'activity_adventure_sports': 'Sports d\'aventure',
      'activity_nightlife_entertainment': 'Vie nocturne & Divertissement',
      'activity_food_gastronomy': 'Cuisine & Gastronomie',
      'activity_shopping': 'Shopping',
      'activity_wellness_spa': 'Bien-être & Spa',
      'duration_unit': 'jours',
      'home_title': 'Accueil',
      'home_welcome': 'Bienvenue',
      'guest_ready_to_travel': 'Prêt à commencer votre voyage ?',
      'guest_create_account_description':
          'Créez votre compte pour sauvegarder vos préférences et accéder à toutes les fonctionnalités',
      'guest_login': 'Se connecter',
      'guest_signup': 'S\'inscrire',
      'guest_unlock_features': 'Débloquez toutes les fonctionnalités',
      'guest_edit_profile': 'Modifier votre profil et préférences',
      'guest_manage_reservations': 'Gérer vos réservations',
      'guest_save_destinations': 'Sauvegarder vos destinations préférées',
      'guest_write_reviews': 'Laisser des avis et commentaires',
      'guest_share_photos': 'Partager vos photos de voyage',
      'home_search_hint': 'Rechercher des destinations, activités...',
      'home_recommendations_title': 'Recommandations près de chez vous',
      'rec_park_title': 'Parc Central',
      'rec_park_subtitle':
          'Un magnifique parc urbain avec des lacs et des sentiers.',
      'rec_museum_title': 'Musée du Louvre',
      'rec_museum_subtitle':
          'Explorez des collections d\'art mondialement célèbres.',
      'home_trending_title': 'Destinations tendances',
      'trending_paris_name': 'Paris',
      'trending_paris_subtitle': 'La Ville Lumière vous attend.',
      'trending_kyoto_name': 'Kyoto',
      'trending_kyoto_subtitle': 'Découvrez des temples et jardins anciens.',
      'home_seasonal_title': 'Points forts saisonniers',
      'seasonal_summer_title': 'Évasions estivales',
      'seasonal_summer_subtitle':
          'Des spots parfaits pour le soleil et la mer.',
      'seasonal_autumn_title': 'Aventures automnales',
      'seasonal_autumn_subtitle':
          'Explorez les feuillages d\'automne et le temps frais.',
      'home_featured_cities_title': 'Villes en vedette',
      'city_nyc_name': 'New York City',
      'city_paris_name': 'Paris',
      'city_tokyo_name': 'Tokyo',
      'tag_business': 'Affaires',
      'tag_art_culture': 'Art & Culture',
      'tag_museums': 'Musées',
      'tag_cultural_attractions': 'Attractions culturelles',
      'tag_technology': 'Technologie',
      'tag_traditional_culture': 'Culture traditionnelle',
      'reviews_label': 'avis',
      'nav_home': 'Accueil',
      'nav_explore': 'Explorer',
      'nav_products': 'Produits',
      'nav_saved': 'Enregistrés',
      'nav_profile': 'Profil',
      'explore_title': 'Explorer le Maroc',
      'explore_subtitle': 'Découvrez des destinations et activités incroyables',
      'products_title': 'Produits Marocains',
      'products_subtitle': 'Achetez des produits artisanaux authentiques',
      'saved_title': 'Vos Éléments Enregistrés',
      'saved_subtitle':
          'Lieux, activités et produits que vous avez enregistrés',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'Gérez votre profil et vos préférences',
      'of': 'de',
      'guest_mode_info': 'Mode invité - Fonctionnalités limitées',
      'guest_mode_description':
          'Vous pouvez explorer l\'application, mais certaines fonctionnalités nécessitent une connexion',
      'login_required': 'Connexion requise',
      'login_required_message':
          'Cette fonctionnalité nécessite une connexion. Souhaitez-vous vous connecter maintenant ?',
      'cancel': 'Annuler',
      'login': 'Se connecter',
      'plan_your_itinerary': 'Planifiez Votre Itinéraire',
      'trip_duration': 'Durée du Voyage',
      'one_day': '1 Jour',
      'two_days': '2 Jours',
      'three_days': '3 Jours',
      'five_days': '5 Jours',
      'days': 'jours',
      'budget': 'Budget',
      'budget_range': 'Gamme de Budget',
      'low_range': 'Économique',
      'mid_range': 'Moyen',
      'high_range': 'Luxe',
      'luxury': 'Luxe',
      'start_date': 'Date de Début',
      'select_date': 'Sélectionner une Date',
      'activities': 'Activités',
      'activities_interests': 'Activités et Intérêts',
      'select_activities':
          'Sélectionnez les activités que vous aimeriez inclure',
      'generate_itinerary': 'Générer l\'Itinéraire',
      'itinerary_generated': 'Itinéraire Généré !',
      'itinerary_success':
          'Votre itinéraire personnalisé a été créé avec succès.',
      'ok': 'OK',
      'share': 'Partager',
      'activity_booked_title': 'Activité réservée !',
      'activity_booked_success': 'Vous avez réservé avec succès :',
      'season': 'Saison',
      'all_year': 'Toute l\'année',
      'share_functionality_coming_soon': 'Le partage arrive bientôt !',
      'route_not_found': 'Route introuvable',
      'search_title': 'Recherche',
      'search_page_title': 'Page de recherche',
      'coming_soon': 'Bientôt disponible...',
      'destination': 'Destination',
      'destination_detail': 'Détail de la destination',
      'detail_page_coming_soon': 'Page de détail bientôt disponible...',

      'activity_detail': 'Détail de l\'activité',

      'product_detail': 'Détail du produit',
      'collection': 'Collection',
      'seasonal_collection': 'Collection saisonnière',
      'collection_page_coming_soon': 'Page de collection bientôt disponible...',
      'settings': 'Paramètres',
      'settings_page_coming_soon': 'Page des paramètres bientôt disponible...',
      'help_support': 'Aide & Support',
      'help_page_coming_soon': 'Page d\'aide bientôt disponible...',
      'error_skipping_questionnaire': 'Erreur lors du saut du questionnaire',
      'error_saving_preferences':
          'Erreur lors de la sauvegarde des préférences',
      'activity_sightseeing': 'Tourisme',
      'activity_food_tour': 'Tour Gastronomique',
      'activity_cultural_visit': 'Visite Culturelle',
      'activity_relaxation': 'Détente',
      'unknown_destination': 'Destination Inconnue',
      // Filter page translations
      'filters': 'Filtres',
      'clear': 'Effacer',
      'category': 'Catégorie',
      'all': 'Tous',
      'cities': 'Villes',
      'culture': 'Culture',
      'nature': 'Nature',
      'adventure': 'Aventure',
      'beach': 'Plage',
      'desert': 'Désert',
      'all_budgets': 'Tous les Budgets',
      'duration': 'Durée',
      'any_duration': 'Toute Durée',
      'weekend': 'Week-end',
      'short_trip': 'Court Voyage',
      'one_week': 'Une Semaine',
      'extended': 'Prolongé',
      'experience_type': 'Type d\'Expérience',
      'apply_filters': 'Appliquer les Filtres',
      // Profile page translations
      'profile': 'Profil',
      'member_since': 'Membre depuis',
      'contribution': 'contribution',
      'contributions': 'contributions',
      'tell_about_yourself': 'Parlez un peu de vous aux autres voyageurs.',
      'no_city_selected': 'Aucune ville sélectionnée.',
      'your_achievements': 'Vos Réalisations',
      'show_all': 'Voir tout',
      'write_first_review': 'Écrivez votre première critique',
      'unlock_levels_reviews': 'Débloquez des niveaux avec des critiques',
      'upload_first_photo': 'Téléchargez votre première photo',
      'unlock_levels_photos': 'Débloquez des niveaux avec des photos',
      'reservations': 'Réservations',
      'preferences': 'Préférences',
      'theme': 'Thème',
      'choose_theme': 'Choisir le Thème',
      'light': 'Clair',
      'dark': 'Sombre',
      'system': 'Système',
      'always_use_light': 'Toujours utiliser le thème clair',
      'always_use_dark': 'Toujours utiliser le thème sombre',
      'follow_system_theme': 'Suivre le thème du système',
      // Edit Profile page translations
      'account_information': 'Informations du Compte',
      'first_name': 'Prénom',
      'last_name': 'Nom de Famille',
      'enter_first_name': 'Entrez votre prénom',
      'enter_last_name': 'Entrez votre nom de famille',
      'home_airport': 'Aéroport de Départ',
      'airport_hint': 'Entrez le code de votre aéroport de départ',
      'enter_email': 'Entrez votre adresse email',
      'full_address': 'Adresse Complète',
      'enter_address': 'Entrez votre adresse complète',
      'address_suite': 'Adresse/Appartement',
      'additional_address_info': 'Informations d\'adresse supplémentaires',
      'city': 'Ville',
      'enter_city': 'Entrez votre ville',
      'state_region_province': 'État/Région/Province',
      'enter_region': 'Entrez votre région',
      'postal_code': 'Code Postal',
      'enter_postal_code': 'Entrez votre code postal',
      'country': 'Pays',
      'select_country': 'Sélectionnez votre pays',
      'france': 'France',
      'spain': 'Espagne',
      'usa': 'États-Unis',
      'phone_number': 'Numéro de Téléphone',
      'renew_password': 'Renouveler le Mot de Passe',
      'save': 'Enregistrer',
      'profile_updated_success': 'Profil mis à jour avec succès !',
      'field_required': 'Ce champ est requis',
      // Trip management translations
      'Trips': 'Voyages',
      'create_trip': 'Créer un Voyage',
      'edit_trip': 'Modifier le Voyage',
      'trip_details': 'Détails du Voyage',
      'trip_name': 'Nom du Voyage',
      'trip_name_required': 'Le nom du voyage est obligatoire',

      'destination_required': 'La destination est obligatoire',
      'end_date': 'Date de Fin',
      'notes': 'Notes',
      'add_activity': 'Ajouter une Activité',
      'no_activities_added': 'Aucune activité ajoutée pour le moment',
      'add_activities_description':
          'Appuyez sur les boutons ci-dessus pour ajouter des activités à votre voyage',
      'save_changes': 'Enregistrer les Modifications',
      'create_your_first_trip':
          'Créez votre premier voyage et commencez à planifier votre aventure',
      'no_trips_saved': 'Aucun voyage enregistré pour le moment',
      'created': 'Créé',
      'edit_activity': 'Modifier l\'Activité',
      'activity_name': 'Nom de l\'Activité',
      'description_optional': 'Description (Optionnel)',
      'location_optional': 'Emplacement (Optionnel)',
      'duration_minutes': 'Durée en minutes (Optionnel)',
      'type': 'Type',
      'custom': 'Personnalisé',
      'attraction': 'Attraction',
      'restaurant': 'Restaurant',
      'hotel': 'Hôtel',
      'transport': 'Transport',
      'add': 'Ajouter',
      'delete_trip': 'Supprimer le Voyage',
      'delete_trip_confirmation':
          'Êtes-vous sûr de vouloir supprimer ce voyage ? Cette action ne peut pas être annulée.',
      'delete': 'Supprimer',
      'trip_created_successfully': 'Voyage créé avec succès !',
      'trip_saved_successfully': 'Voyage enregistré avec succès !',
      'error_creating_trip': 'Erreur lors de la création du voyage',
      'error_saving_trip': 'Erreur lors de l\'enregistrement du voyage',
      'please_select_dates':
          'Veuillez sélectionner les dates de début et de fin',
      'start_date_after_end_date':
          'La date de début doit être antérieure à la date de fin',
      'please_select_destination':
          'Veuillez d\'abord sélectionner une destination',
      'add_existing_activities': 'Ajouter des Activités Existantes',
      'add_activities_from': 'Ajouter des Activités de',
      'search_activities': 'Rechercher des activités...',
      'no_attractions_found':
          'Aucune attraction trouvée pour cette destination',
      'save_selected': 'Enregistrer',
      'selected_activities': 'Activités Sélectionnées',
      'trip_deleted_successfully': 'Voyage supprimé avec succès',
      'error_deleting_trip': 'Erreur lors de la suppression du voyage',
      'choose_from_gallery': 'Choisir depuis la Galerie',
      'take_photo': 'Prendre une Photo',
      // Wishlist/Saved page translations
      'products': 'Produits',
      'no_activities_saved': 'Aucune activité sauvegardée pour le moment',
      'start_exploring_activities':
          'Commencez à explorer et sauvegardez vos activités préférées',
      'explore_activities': 'Explorer les Activités',
      'no_cities_saved': 'Aucune ville sauvegardée pour le moment',
      'save_cities_visit': 'Sauvegardez les villes que vous voulez visiter',
      'explore_cities': 'Explorer les Villes',
      'no_products_saved': 'Aucun produit sauvegardé pour le moment',
      'save_products_buy': 'Sauvegardez les produits que vous voulez acheter',
      'explore_products': 'Explorer les Produits',
      'activity': 'Activité',
      'location': 'Emplacement',
      'price': 'Prix',
      // Explore page translations
      'explore_morocco': 'Explorer le Maroc',
      'search_cities_activities': 'Rechercher des villes, activités...',
      'categories': 'Catégories',
      'popular_cities': 'Villes Populaires',
      'recommended_activities': 'Activités Recommandées',
      'upcoming_events': 'Événements à Venir',
      'view_all': 'Voir Tout',
      'marrakech': 'Marrakech',
      'fes': 'Fès',
      'chefchaouen': 'Chefchaouen',
      'sahara_desert_safari': 'Safari dans le Désert du Sahara',
      'marrakech_medina_tour': 'Tour de la Médina de Marrakech',
      'moroccan_cooking_class': 'Cours de Cuisine Marocaine',
      'cinema_world_music_festival': 'Festival de Musique du Monde de Cinéma',
      'rose_festival': 'Festival des Roses',
      'essaouira': 'Essaouira',
      'kelaat_mgouna': 'Kelaat M\'Gouna',
      'june_10_15': '10-15 Juin',
      'may_10_12': '10-12 Mai',
      // Products page translations
      '2_4_hours': '2-4 heures',
      '3_4_hours': '3-4 heures',
      '2_3_hours': '2-3 heures',
      '1_2_hours': '1-2 heures',
      '4_6_hours': '4-6 heures',
      // Search page translations
      'search_morocco': 'Rechercher le Maroc',
      'search_cities_activities_hint': 'Rechercher des villes, activités...',
      'search_for_cities_activities':
          'Recherchez des villes, activités ou attractions',
      'no_results_found': 'Aucun résultat trouvé pour',
      'try_different_keywords':
          'Essayez différents mots-clés ou vérifiez l\'orthographe',
      // Details page translations
      'key_attractions': 'Attractions Principales',
      'location_on_map': 'Emplacement sur la Carte',
      'map_view': 'Vue Carte',
      'explore_the_souks': 'Explorer les Souks',
      'visit_secret_garden': 'Visiter le Jardin Secret',
      'enjoy_traditional_hammam': 'Profiter d\'un Hammam Traditionnel',
      'hot_air_balloon_ride': 'Balade en Montgolfière',
      'various_locations': 'Divers emplacements',
      'medina': 'Médina',
      'palmerale': 'Palmeraie',
      // Enhanced Welcome Screen translations
      'choose_your_city': 'Choisissez votre ville',
      'detecting_location': 'Détection de votre localisation...',
      'selected_city_info': 'Informations sur la ville',
      // Preferences page translations
      'language': 'Langue',
      // Reservations page translations
      'no_reservations_yet': 'Pas encore de réservations ? Corrigeons cela !',
      'book_before_you_go':
          'Réservez avant de partir pour découvrir le meilleur sur place.',
      'start_planning': 'Commencer à planifier',
      'new_trip': 'Nouveau Voyage',
      'explore': 'Explorer',
      'logout': 'Déconnexion',
      // Wishlist translations
      'wishlist': 'Liste de souhaits',
      'currency': 'Devise',
      'payment_method': 'Méthode de paiement',
      'card_number': 'Numéro de carte',
      'expiry': 'Expiration',
      'cvc': 'CVC',
      'cardholder_name': 'Nom du titulaire',
      'name_on_card': 'Nom sur la carte',
      'payment_info_saved': 'Informations de paiement sauvegardées !',
      'euro': 'Euro',
      'mad': 'Dirham marocain',
      'dollar': 'Dollar américain',
      'retry': 'Réessayer',
      'book_now': 'Réserver maintenant',
      'added_to_wishlist': 'Ajouté à la liste de souhaits',
      'removed_from_wishlist': 'Supprimé de la liste de souhaits',
      'view_details': 'Voir les détails',
      'error_booking_activity': 'Erreur lors de la réservation de l\'activité',
      'city_label_colon': 'Ville :',
      'loading_cities': 'Chargement des villes...',
      'all_cities': 'Toutes les villes',
      'get_directions': 'Obtenir l\'itinéraire',
      'directions_functionality_coming_soon': 'Fonctionnalité d\'itinéraire bientôt disponible !',
      'phone_hint_example': '+212 6XX XX XX XX',
      'search_cities_countries_activities_hint': 'Rechercher des villes, pays ou activités...',
      'otp_hint': '------',
      // Panier & Paiement
      'shopping_cart': 'Panier',
      'failed_load_cart_items': 'Échec du chargement du panier',
      'cart_empty_title': 'Votre panier est vide',
      'cart_empty_subtitle': 'Ajoutez des produits pour commencer !',
      'continue_shopping': 'Continuer vos achats',
      'total': 'Total :',
      'proceed_to_checkout': 'Passer au paiement',
      'checkout': 'Paiement',
      'place_order': 'Passer la commande',
      'order_summary': 'Récapitulatif de la commande',
      'qty': 'Qté',
      'shipping_information': 'Informations de livraison',
      'enter_full_name': 'Veuillez entrer votre nom complet',
      'enter_valid_email': 'Veuillez entrer une adresse email valide',
      'enter_phone_number': 'Veuillez entrer votre numéro de téléphone',

      'credit_card': 'Carte bancaire',
      'pay_with_credit_card': 'Payer avec votre carte bancaire',
      'pay_with_paypal': 'Payer avec votre compte PayPal',
      'cash_on_delivery': 'Paiement à la livraison',
      'pay_on_delivery': 'Payer à la réception de la commande',
    },
    'العربية': {
      'skip': 'تخطي',
      'welcome_title': 'مرحباً بك في المغرب',
      'welcome_subtitle':
          'اكتشف طريقة جديدة للتواصل والاستكشاف.\nابدأ رحلتك اليوم!',
      'select_language': 'اختر اللغة',
      'get_started': 'ابدأ',
      'already_account': 'هل لديك حساب بالفعل؟ ',
      'log_in': 'تسجيل الدخول',
      'morocco': 'المغرب',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'مرحباً بعودتك! يرجى إدخال بياناتك.',
      'email_phone_label': 'البريد الإلكتروني أو الهاتف',
      'email_phone_hint': 'أدخل بريدك الإلكتروني أو رقم الهاتف',
      'email_phone_error': 'يرجى إدخال بريدك الإلكتروني أو رقم الهاتف',
      'email_phone_invalid': 'يرجى إدخال بريد إلكتروني أو رقم هاتف صحيح',
      'username_email_label': 'اسم المستخدم أو البريد الإلكتروني',
      'username_email_hint': 'أدخل اسم المستخدم أو البريد الإلكتروني',
      'username_email_error': 'يرجى إدخال اسم المستخدم أو البريد الإلكتروني',
      'username_email_invalid': 'يرجى إدخال اسم مستخدم أو بريد إلكتروني صحيح',
      'password_label': 'كلمة المرور',
      'password_hint': 'أدخل كلمة المرور',
      'password_error': 'يرجى إدخال كلمة المرور',
      'remember_me': 'تذكرني',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login_button': 'تسجيل الدخول',
      'or_continue_with': 'أو المتابعة باستخدام',
      'no_account': 'ليس لديك حساب؟ ',
      'sign_up': 'إنشاء حساب',
      'login_success': 'تم تسجيل الدخول بنجاح!',
      'login_failed': 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
      'sign_up_google': 'تسجيل الدخول باستخدام Google',
      'sign_up_apple': 'تسجيل الدخول باستخدام Apple',
      'sign_up_facebook': 'تسجيل الدخول باستخدام Facebook',
      'forgot_password_title': 'نسيت كلمة المرور ؟',
      'forgot_password_subtitle':
          'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.',
      'forgot_password_email_hint': 'أدخل بريدك الإلكتروني',
      'send_reset_link': 'إرسال رابط إعادة تعيين كلمة المرور',
      'back_to_login': 'العودة إلى تسجيل الدخول',
      'google_login_todo':
          'تسجيل الدخول بجوجل - سيتم تنفيذه مع google_sign_in package',
      'apple_login_todo':
          'تسجيل الدخول بآبل - سيتم تنفيذه مع sign_in_with_apple package',
      'facebook_login_todo':
          'تسجيل الدخول بفيسبوك - سيتم تنفيذه مع flutter_facebook_auth package',
      'email_label': 'البريد الإلكتروني',
      'reset_link_sent': 'تم إرسال رابط إعادة التعيين!',
      'reset_link_instructions':
          'يرجى التحقق من بريدك الوارد واتباع التعليمات الخاصة برابط إعادة تعيين كلمة المرور.',
      'create_account': 'إنشاء حساب',
      'full_name_label': 'الاسم الكامل',
      'full_name_hint': 'أدخل اسمك الكامل',
      'confirm_password_label': 'تأكيد كلمة المرور',
      'confirm_password_hint': 'تأكيد كلمة المرور الخاصة بك',
      'travel_preferences_title': 'تفضيلات السفر',
      'duration_question': 'كم من الوقت تخطط للسفر؟',
      'duration_question_title': 'مدة السفر',
      'budget_question': 'ما هو ميزانيتك التقريبية؟',
      'budget_question_title': 'تفضيل الميزانية',
      'activities_question': 'ما أنواع الأنشطة التي تهمك؟',
      'activities_question_title': 'تفضيلات الأنشطة',
      'accommodation_question': 'ما نوع الإقامة التي تفضلها؟',
      'accommodation_question_title': 'نوع الإقامة',
      'group_size_question': 'من تسافر معهم؟',
      'group_size_question_title': 'حجم المجموعة',
      'transportation_question_title': 'تفضيل النقل',
      'multiple_choice_instruction': 'اختر جميع الخيارات التي تهمك',
      'Next': 'التالي',
      'finish': 'إنهاء',
      'skip_button': 'تأجيل لاحقًا',
      'preferences_saved': '✅ تم حفظ التفضيلات بنجاح!',
      'preferences_saved_success': 'تم حفظ التفضيلات بنجاح!',
      'welcome_preferences_title': 'خصص تجربتك',
      'welcome_preferences_subtitle': 'ساعدنا في التوصية بأفضل الوجهات لك',
      'previous': 'السابق',

      'budget_economic': 'اقتصادي (< 500 درهم/يوم)',
      'budget_moderate': 'متوسط (500-1500 درهم/يوم)',
      'budget_luxury': 'فاخر (> 1500 درهم/يوم)',
      'budget_friendly': 'ميزانية منخفضة',
      'activity_culture': 'الثقافة والتاريخ',
      'activity_nature': 'الطبيعة والتسلق',
      'activity_beach': 'الشاطئ والاسترخاء',
      'activity_adventure': 'الرياضة والمغامرة',
      'activity_nightlife': 'الحياة الليلية',
      'activity_gastronomy': 'المأكولات',
      'accommodation_hotel': 'فندق',
      'accommodation_hostel': 'دار شباب',
      'accommodation_airbnb': 'إيربي إن/تأجير',
      'accommodation_camping': 'تخييم',
      'accommodation_luxury_hotel': 'فندق فاخر',
      'accommodation_boutique_hotel': 'فندق بوتيك',
      'accommodation_business_hotel': 'فندق أعمال',
      'accommodation_budget_hotel': 'فندق اقتصادي',
      'accommodation_resort': 'منتجع',
      'accommodation_riad': 'رياض',
      'accommodation_guesthouse': 'بيت ضيافة',
      'accommodation_apartment': 'شقة',
      'accommodation_villa': 'فيلا',
      'group_solo': 'بمفردي',
      'group_couple': 'كزوج',
      'group_family': 'مع العائلة',
      'group_friends': 'مع الأصدقاء',
      'group_family_kids': 'عائلة مع أطفال',
      'group_family_adults': 'عائلة مع بالغين',
      'group_friends_small': 'مجموعة صغيرة من الأصدقاء',
      'group_friends_large': 'مجموعة كبيرة من الأصدقاء',
      'transportation_flight': 'رحلة جوية',
      'transportation_car_rental': 'تأجير سيارة',
      'transportation_private_driver': 'سائق خاص',
      'transportation_public_transport': 'نقل عام',
      'transportation_train': 'قطار',
      'transportation_taxi_ride_share': 'تاكسي/مشاركة الركوب',
      'transportation_bicycle': 'دراجة هوائية',
      'transportation_walking': 'المشي',
      'activity_culture_history': 'الثقافة والتاريخ',
      'activity_nature_wildlife': 'الطبيعة والحياة البرية',
      'activity_beach_water': 'الشاطئ والأنشطة المائية',
      'activity_adventure_sports': 'رياضات المغامرة',
      'activity_nightlife_entertainment': 'الحياة الليلية والترفيه',
      'activity_food_gastronomy': 'الطعام والمأكولات',
      'activity_shopping': 'التسوق',
      'activity_wellness_spa': 'الرفاهية والسبا',
      'duration_unit': 'أيام',
      'home_title': 'الرئيسية',
      'home_welcome': 'أهلاً',
      'guest_ready_to_travel': 'هل أنت مستعد لبدء رحلتك؟',
      'guest_create_account_description':
          'أنشئ حسابك لحفظ تفضيلاتك والوصول إلى جميع الميزات',
      'guest_login': 'تسجيل الدخول',
      'guest_signup': 'إنشاء حساب',
      'guest_unlock_features': 'افتح جميع الميزات',
      'guest_edit_profile': 'تعديل ملفك الشخصي وتفضيلاتك',
      'guest_manage_reservations': 'إدارة حجوزاتك',
      'guest_save_destinations': 'حفظ وجهاتك المفضلة',
      'guest_write_reviews': 'كتابة تقييمات وتعليقات',
      'guest_share_photos': 'مشاركة صور سفرك',
      'home_search_hint': 'ابحث عن وجهات، أنشطة...',
      'home_recommendations_title': 'التوصيات القريبة منك',
      'rec_park_title': 'الحديقة المركزية',
      'rec_park_subtitle': 'حديقة حضرية رائعة تحتوي على بحيرات ومسارات.',
      'rec_museum_title': 'متحف اللوفر',
      'rec_museum_subtitle': 'استكشف مجموعات فنية عالمية الشهرة.',
      'home_trending_title': 'وجهات متصدرة',
      'trending_paris_name': 'باريس',
      'trending_paris_subtitle': 'مدينة النور تنتظرك.',
      'trending_kyoto_name': 'كيوتو',
      'trending_kyoto_subtitle': 'اكتشف المعابد والحدائق القديمة.',
      'home_seasonal_title': 'نقاط بارزة موسمية',
      'seasonal_summer_title': 'ملاذات الصيف',
      'seasonal_summer_subtitle': 'أماكن مثالية للشمس والبحر.',
      'seasonal_autumn_title': 'مغامرات الخريف',
      'seasonal_autumn_subtitle': 'استكشف أوراق الخريف والطقس البارد.',
      'home_featured_cities_title': 'مدن مميزة',
      'city_nyc_name': 'نيويورك',
      'city_paris_name': 'باريس',
      'city_tokyo_name': 'طوكيو',
      'tag_business': 'أعمال',
      'tag_art_culture': 'فن وثقافة',
      'tag_museums': 'متاحف',
      'tag_cultural_attractions': 'معالم ثقافية',
      'tag_technology': 'تكنولوجيا',
      'tag_traditional_culture': 'ثقافة تقليدية',
      'reviews_label': 'تقييمات',
      'nav_home': 'الرئيسية',
      'nav_explore': 'استكشاف',
      'nav_products': 'المنتجات',
      'nav_saved': 'تم الحفظ',
      'nav_profile': 'الملف الشخصي',
      'explore_title': 'استكشف المغرب',
      'explore_subtitle': 'اكتشف وجهات وأنشطة مذهلة',
      'products_title': 'المنتجات المغربية',
      'products_subtitle': 'تسوق منتجات يدوية أصيلة',
      'saved_title': 'عناصرك المحفوظة',
      'saved_subtitle': 'الأماكن والأنشطة والمنتجات التي حافظت عليها',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'إدارة ملفك الشخصي وتفضيلاتك',
      'of': 'من',
      // Trip management translations
      'Trips': 'الرحلات',
      'create_trip': 'إنشاء رحلة',
      'edit_trip': 'تعديل الرحلة',
      'trip_details': 'تفاصيل الرحلة',
      'trip_name': 'اسم الرحلة',
      'trip_name_required': 'اسم الرحلة مطلوب',

      'destination_required': 'الوجهة مطلوبة',
      'start_date': 'تاريخ البداية',
      'end_date': 'تاريخ النهاية',
      'notes': 'ملاحظات',
      'activities': 'الأنشطة',
      'add_activity': 'إضافة نشاط',
      'no_activities_added': 'لم يتم إضافة أنشطة بعد',
      'add_activities_description':
          'اضغط على الأزرار أعلاه لإضافة أنشطة لرحلتك',
      'save_changes': 'حفظ التغييرات',
      'create_your_first_trip': 'أنشئ رحلتك الأولى وابدأ في تخطيط مغامرتك',
      'no_trips_saved': 'لم يتم حفظ رحلات بعد',
      'created': 'تم الإنشاء',
      'edit_activity': 'تعديل النشاط',
      'activity_name': 'اسم النشاط',
      'description_optional': 'الوصف (اختياري)',
      'location_optional': 'الموقع (اختياري)',
      'duration_minutes': 'المدة بالدقائق (اختياري)',
      'type': 'النوع',
      'custom': 'مخصص',
      'attraction': 'معلم سياحي',
      'restaurant': 'مطعم',
      'hotel': 'فندق',
      'transport': 'نقل',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'save': 'حفظ',
      'delete_trip': 'حذف الرحلة',
      'delete_trip_confirmation':
          'هل أنت متأكد من أنك تريد حذف هذه الرحلة؟ لا يمكن التراجع عن هذا الإجراء.',
      'delete': 'حذف',
      'trip_created_successfully': 'تم إنشاء الرحلة بنجاح!',
      'trip_saved_successfully': 'تم حفظ الرحلة بنجاح!',
      'error_creating_trip': 'خطأ في إنشاء الرحلة',
      'error_saving_trip': 'خطأ في حفظ الرحلة',
      'please_select_dates': 'يرجى تحديد تواريخ البداية والنهاية',
      'start_date_after_end_date':
          'يجب أن تكون تاريخ البداية قبل تاريخ النهاية',
      'please_select_destination': 'يرجى تحديد وجهة أولاً',
      'add_existing_activities': 'إضافة أنشطة موجودة',
      'add_activities_from': 'إضافة أنشطة من',
      'search_activities': 'البحث عن الأنشطة...',
      'no_attractions_found': 'لم يتم العثور على معالم سياحية لهذه الوجهة',
      'save_selected': 'حفظ',
      'selected_activities': 'الأنشطة المختارة',
      'trip_deleted_successfully': 'تم حذف الرحلة بنجاح',
      'error_deleting_trip': 'خطأ في حذف الرحلة',
      'guest_mode_info': 'الوضع الضيف - ميزات محدودة',
      'guest_mode_description':
          'يمكنك استكشاف التطبيق، لكن بعض الميزات تتطلب تسجيل الدخول',
      'login_required': 'تسجيل الدخول مطلوب',
      'login_required_message':
          'هذه الميزة تتطلب تسجيل الدخول. هل تريد تسجيل الدخول الآن؟',
      'login': 'تسجيل الدخول',
      'plan_your_itinerary': 'خطط رحلتك',
      'trip_duration': 'مدة الرحلة',
      'one_day': 'يوم واحد',
      'two_days': 'يومان',
      'three_days': 'ثلاثة أيام',
      'five_days': 'خمسة أيام',
      'days': 'أيام',
      'budget': 'الميزانية',
      'budget_range': 'نطاق الميزانية',
      'low_range': 'اقتصادي',
      'mid_range': 'متوسط',
      'high_range': 'فاخر',
      'luxury': 'فاخر',
      'select_date': 'اختر التاريخ',
      'activities_interests': 'الأنشطة والاهتمامات',
      'select_activities': 'حدد الأنشطة التي تود تضمينها',
      'generate_itinerary': 'أنشئ رحلتك',
      'itinerary_generated': 'تم إنشاء رحلتك!',
      'itinerary_success': 'تم إنشاء رحلتك الشخصية بنجاح.',
      'ok': 'موافق',
      'share': 'مشاركة',
      'activity_booked_title': 'تم حجز النشاط!',
      'activity_booked_success': 'لقد تم الحجز بنجاح:',
      'season': 'الموسم',
      'all_year': 'طوال العام',
      'share_functionality_coming_soon': 'ميزة المشاركة قريباً!',
      'route_not_found': 'المسار غير موجود',
      'search_title': 'بحث',
      'search_page_title': 'صفحة البحث',
      'coming_soon': 'قريباً...',
      'destination': 'الوجهة',
      'destination_detail': 'تفاصيل الوجهة',
      'detail_page_coming_soon': 'صفحة التفاصيل قريباً...',

      'activity_detail': 'تفاصيل النشاط',

      'product_detail': 'تفاصيل المنتج',
      'collection': 'المجموعة',
      'seasonal_collection': 'مجموعة موسمية',
      'collection_page_coming_soon': 'صفحة المجموعة قريباً...',
      'settings': 'الإعدادات',
      'settings_page_coming_soon': 'صفحة الإعدادات قريباً...',
      'help_support': 'المساعدة والدعم',
      'help_page_coming_soon': 'صفحة المساعدة قريباً...',
      'error_skipping_questionnaire': 'خطأ أثناء تجاوز الاستبيان',
      'error_saving_preferences': 'خطأ أثناء حفظ التفضيلات',
      'activity_sightseeing': 'جولة سياحية',
      'activity_food_tour': 'جولة طعام',
      'activity_cultural_visit': 'زيارة ثقافية',
      'activity_relaxation': 'استرخاء',
      'unknown_destination': 'وجهة غير معروفة',
      // Filter page translations
      'filters': 'المرشحات',
      'clear': 'مسح',
      'category': 'الفئة',
      'all': 'الكل',
      'cities': 'المدن',
      'culture': 'الثقافة',
      'nature': 'الطبيعة',
      'adventure': 'مغامرة',
      'beach': 'شاطئ',
      'desert': 'صحراء',
      'all_budgets': 'جميع الميزانيات',
      'duration': 'المدة',
      'any_duration': 'أي مدة',
      'weekend': 'عطلة نهاية الأسبوع',
      'short_trip': 'رحلة قصيرة',
      'one_week': 'أسبوع واحد',
      'extended': 'ممتد',
      'experience_type': 'نوع التجربة',
      'apply_filters': 'تطبيق المرشحات',
      // Profile page translations
      'profile': 'الملف الشخصي',
      'member_since': 'عضو منذ',
      'contribution': 'مساهمة',
      'contributions': 'مساهمات',
      'tell_about_yourself': 'أخبر المسافرين الآخرين قليلاً عن نفسك.',
      'no_city_selected': 'لم يتم اختيار مدينة.',
      'your_achievements': 'إنجازاتك',
      'show_all': 'عرض الكل',
      'write_first_review': 'اكتب مراجعتك الأولى',
      'unlock_levels_reviews': 'افتح المستويات بالمراجعات',
      'upload_first_photo': 'حمّل صورتك الأولى',
      'unlock_levels_photos': 'افتح المستويات بالصور',
      'reservations': 'الحجوزات',
      'preferences': 'التفضيلات',
      'theme': 'المظهر',
      'choose_theme': 'اختر المظهر',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'النظام',
      'always_use_light': 'استخدم المظهر الفاتح دائماً',
      'always_use_dark': 'استخدم المظهر الداكن دائماً',
      'follow_system_theme': 'اتبع مظهر النظام',
      // Edit Profile page translations
      'account_information': 'معلومات الحساب',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'enter_first_name': 'أدخل اسمك الأول',
      'enter_last_name': 'أدخل اسم العائلة',
      'home_airport': 'مطار المنزل',
      'airport_hint': 'أدخل رمز مطار منزلك',
      'enter_email': 'أدخل عنوان بريدك الإلكتروني',
      'full_address': 'العنوان الكامل',
      'enter_address': 'أدخل عنوانك الكامل',
      'address_suite': 'العنوان/الجناح',
      'additional_address_info': 'معلومات عنوان إضافية',
      'city': 'المدينة',
      'enter_city': 'أدخل مدينتك',
      'state_region_province': 'الولاية/المنطقة/المحافظة',
      'enter_region': 'أدخل منطقتك',
      'postal_code': 'الرمز البريدي',
      'enter_postal_code': 'أدخل الرمز البريدي',
      'country': 'البلد',
      'select_country': 'اختر بلدك',
      'france': 'فرنسا',
      'spain': 'إسبانيا',
      'usa': 'الولايات المتحدة',
      'phone_number': 'رقم الهاتف',
      'renew_password': 'تجديد كلمة المرور',
      'profile_updated_success': 'تم تحديث الملف الشخصي بنجاح!',
      'field_required': 'هذا الحقل مطلوب',
      'choose_from_gallery': 'اختر من المعرض',
      'take_photo': 'التقاط صورة',
      // Wishlist/Saved page translations
      'products': 'المنتجات',
      'no_activities_saved': 'لا توجد أنشطة محفوظة بعد',
      'start_exploring_activities': 'ابدأ الاستكشاف واحفظ أنشطتك المفضلة',
      'explore_activities': 'استكشف الأنشطة',
      'no_cities_saved': 'لا توجد مدن محفوظة بعد',
      'save_cities_visit': 'احفظ المدن التي تريد زيارتها',
      'explore_cities': 'استكشف المدن',
      'no_products_saved': 'لا توجد منتجات محفوظة بعد',
      'save_products_buy': 'احفظ المنتجات التي تريد شراؤها',
      'explore_products': 'استكشف المنتجات',
      'activity': 'النشاط',
      'location': 'الموقع',
      'price': 'السعر',
      // Explore page translations
      'explore_morocco': 'استكشف المغرب',
      'search_cities_activities': 'البحث عن المدن والأنشطة...',
      'categories': 'الفئات',
      'popular_cities': 'المدن الشائعة',
      'recommended_activities': 'الأنشطة الموصى بها',
      'upcoming_events': 'الأحداث القادمة',
      'view_all': 'عرض الكل',
      'marrakech': 'مراكش',
      'fes': 'فاس',
      'chefchaouen': 'شفشاون',
      'sahara_desert_safari': 'رحلة سفاري في الصحراء',
      'marrakech_medina_tour': 'جولة في المدينة القديمة بمراكش',
      'moroccan_cooking_class': 'دورة الطبخ المغربي',
      'cinema_world_music_festival': 'مهرجان الموسيقى العالمية',
      'rose_festival': 'مهرجان الورود',
      'essaouira': 'الصويرة',
      'kelaat_mgouna': 'قلعة مكونة',
      'june_10_15': '10-15 يونيو',
      'may_10_12': '10-12 مايو',
      // Products page translations
      // Itinerary planning translations
      '2_4_hours': '2-4 ساعات',
      '3_4_hours': '3-4 ساعات',
      '2_3_hours': '2-3 ساعات',
      '1_2_hours': '1-2 ساعة',
      '4_6_hours': '4-6 ساعات',
      // Search page translations
      'search_morocco': 'البحث في المغرب',
      'search_cities_activities_hint': 'البحث عن المدن والأنشطة...',
      'search_for_cities_activities':
          'ابحث عن المدن أو الأنشطة أو المعالم السياحية',
      'no_results_found': 'لم يتم العثور على نتائج لـ',
      'try_different_keywords': 'جرب كلمات مفتاحية مختلفة أو تحقق من الإملاء',
      // Details page translations
      'key_attractions': 'المعالم الرئيسية',
      'location_on_map': 'الموقع على الخريطة',
      'map_view': 'عرض الخريطة',
      'explore_the_souks': 'استكشف الأسواق',
      'visit_secret_garden': 'زيارة الحديقة السرية',
      'enjoy_traditional_hammam': 'استمتع بحمام تقليدي',
      'hot_air_balloon_ride': 'رحلة بالمنطاد الهوائي',
      'various_locations': 'مواقع مختلفة',
      'medina': 'المدينة القديمة',
      'palmerale': 'النخيل',
      // Enhanced Welcome Screen translations
      'choose_your_city': 'اختر مدينتك',
      'detecting_location': 'جاري تحديد موقعك...',
      'selected_city_info': 'معلومات المدينة',
      // Preferences page translations
      'language': 'اللغة',
      // Reservations page translations
      'no_reservations_yet': 'لا توجد حجوزات بعد؟ دعنا نصلح ذلك!',
      'book_before_you_go': 'احجز قبل الذهاب لاكتشاف الأفضل في الموقع.',
      'start_planning': 'ابدأ التخطيط',
      'new_trip': 'رحلة جديدة',
      'explore': 'استكشف',
      'logout': 'تسجيل الخروج',
      // Wishlist translations
      'wishlist': 'قائمة الرغبات',
      'currency': 'العملة',
      'payment_method': 'طريقة الدفع',
      'card_number': 'رقم البطاقة',
      'expiry': 'تاريخ الانتهاء',
      'cvc': 'رمز الأمان',
      'cardholder_name': 'اسم حامل البطاقة',
      'name_on_card': 'الاسم على البطاقة',
      'payment_info_saved': 'تم حفظ معلومات الدفع !',
      'euro': 'يورو',
      'mad': 'درهم مغربي',
      'dollar': 'دولار أمريكي',
      'retry': 'إعادة المحاولة',
      'book_now': 'احجز الآن',
      'added_to_wishlist': 'تمت الإضافة إلى قائمة الرغبات',
      'removed_from_wishlist': 'تمت الإزالة من قائمة الرغبات',
      'view_details': 'عرض التفاصيل',
      'error_booking_activity': 'خطأ أثناء حجز النشاط',
      'city_label_colon': 'المدينة:',
      'loading_cities': 'جاري تحميل المدن...',
      'all_cities': 'كل المدن',
      'get_directions': 'احصل على الاتجاهات',
      'directions_functionality_coming_soon': 'ميزة الاتجاهات قريبًا!',
      'phone_hint_example': '+212 6XX XX XX XX',
      'search_cities_countries_activities_hint': 'ابحث عن المدن أو البلدان أو الأنشطة...',
      'otp_hint': '------',
      // عربة التسوق والدفع
      'shopping_cart': 'سلة التسوق',
      'failed_load_cart_items': 'فشل في تحميل عناصر السلة',
      'cart_empty_title': 'سلة التسوق فارغة',
      'cart_empty_subtitle': 'أضف بعض المنتجات للبدء!',
      'continue_shopping': 'متابعة التسوق',
      'total': 'الإجمالي:',
      'proceed_to_checkout': 'المتابعة للدفع',
      'checkout': 'الدفع',
      'place_order': 'إتمام الطلب',
      'order_summary': 'ملخص الطلب',
      'qty': 'الكمية',
      'shipping_information': 'معلومات الشحن',
      'enter_full_name': 'يرجى إدخال اسمك الكامل',
      'enter_valid_email': 'يرجى إدخال بريد إلكتروني صالح',

      'credit_card': 'بطاقة ائتمان',
      'pay_with_credit_card': 'الدفع بواسطة بطاقة الائتمان',
      'pay_with_paypal': 'الدفع بواسطة حساب باي بال',
      'cash_on_delivery': 'الدفع عند الاستلام',
      'pay_on_delivery': 'ادفع عند وصول طلبك',
    },
    'Español': {
      'skip': 'Saltar',
      'welcome_title': 'Bienvenido a Marruecos',
      'welcome_subtitle':
          'Descubre una nueva forma de conectar y explorar.\n¡Comienza tu viaje hoy!',
      'select_language': 'Seleccionar idioma',
      'get_started': 'Empezar',
      'already_account': '¿Ya tienes una cuenta? ',
      'log_in': 'Iniciar sesión',
      'morocco': 'Marruecos',
      'login_title': 'Iniciar sesión',
      'login_subtitle': '¡Bienvenido de vuelta! Por favor, ingresa tus datos.',
      'email_phone_label': 'Email o Teléfono',
      'email_phone_hint': 'Ingresa tu email o teléfono',
      'email_phone_error': 'Por favor ingresa tu email o teléfono',
      'email_phone_invalid':
          'Por favor ingresa un email o número de teléfono válido',
      'username_email_label': 'Nombre de usuario o Email',
      'username_email_hint': 'Ingresa tu nombre de usuario o email',
      'username_email_error': 'Por favor ingresa tu nombre de usuario o email',
      'username_email_invalid':
          'Por favor ingresa un nombre de usuario o email válido',
      'password_label': 'Contraseña',
      'password_hint': 'Ingresa tu contraseña',
      'password_error': 'Por favor ingresa tu contraseña',
      'remember_me': 'Recordarme',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'login_button': 'Iniciar sesión',
      'or_continue_with': 'O continúa con',
      'no_account': '¿No tienes una cuenta? ',
      'sign_up': 'Registrarse',
      'login_success': '¡Inicio de sesión exitoso!',
      'login_failed': 'Error al iniciar sesión. Por favor, inténtalo de nuevo.',
      'sign_up_google': 'Iniciar sesión con Google',
      'sign_up_apple': 'Iniciar sesión con Apple',
      'sign_up_facebook': 'Iniciar sesión con Facebook',
      'forgot_password_title': '¿Contraseña olvidada?',
      'forgot_password_subtitle':
          'Ingresa tu correo electrónico para recibir un enlace de restablecimiento.',
      'forgot_password_email_hint': 'Ingresa tu correo electrónico',
      'send_reset_link': 'Enviar enlace de restablecimiento',
      'back_to_login': 'Volver al inicio de sesión',
      'google_login_todo':
          'Login Google - A implementar con google_sign_in package',
      'apple_login_todo':
          'Login Apple - A implementar con sign_in_with_apple package',
      'facebook_login_todo':
          'Login Facebook - A implementar con flutter_facebook_auth package',
      'email_label': 'Correo electrónico',
      'reset_link_sent': '¡Enlace de restablecimiento enviado!',
      'reset_link_instructions':
          'Por favor revisa tu bandeja de entrada y sigue las instrucciones del enlace de restablecimiento de contraseña.',
      'create_account': 'Crear cuenta',
      'full_name_label': 'Nombre completo',
      'full_name_hint': 'Ingresa tu nombre completo',
      'confirm_password_label': 'Confirmar contraseña',
      'confirm_password_hint': 'Confirma tu contraseña',
      'travel_preferences_title': 'Preferencias de viaje',
      'duration_question': '¿Cuánto tiempo planeas viajar?',
      'duration_question_title': 'Duración del viaje',
      'budget_question': '¿Cuál es tu presupuesto aproximado?',
      'budget_question_title': 'Preferencia de presupuesto',
      'activities_question': '¿Qué tipos de actividades te interesan?',
      'activities_question_title': 'Preferencias de actividades',
      'accommodation_question': '¿Qué tipo de alojamiento prefieres?',
      'accommodation_question_title': 'Tipo de alojamiento',
      'group_size_question': '¿Con quién viajas?',
      'group_size_question_title': 'Tamaño del grupo',
      'transportation_question_title': 'Preferencia de transporte',
      'multiple_choice_instruction':
          'Selecciona todas las opciones que te interesen',
      'Next': 'Siguiente',
      'finish': 'Finalizar',
      'skip_button': 'Omitir para más tarde',
      'preferences_saved': '✅ ¡Preferencias guardadas con éxito!',
      'preferences_saved_success': '¡Preferencias guardadas con éxito!',
      'welcome_preferences_title': 'Personaliza tu experiencia',
      'welcome_preferences_subtitle':
          'Ayúdanos a recomendarte los mejores destinos',
      'previous': 'Anterior',
      'next': 'Siguiente',

      'budget_economic': 'Económico (< 500 DH/día)',
      'budget_moderate': 'Moderado (500-1500 DH/día)',
      'budget_luxury': 'Lujoso (> 1500 DH/día)',
      'budget_friendly': 'Económico',
      'activity_culture': 'Cultura e Historia',
      'activity_nature': 'Naturaleza y Senderismo',
      'activity_beach': 'Playa y Relajación',
      'activity_adventure': 'Deportes y Aventura',
      'activity_nightlife': 'Vida nocturna',
      'activity_gastronomy': 'Gastronomía',
      'accommodation_hotel': 'Hotel',
      'accommodation_hostel': 'Albergue juvenil',
      'accommodation_airbnb': 'Airbnb/Alquiler',
      'accommodation_camping': 'Camping',
      'accommodation_luxury_hotel': 'Hotel de lujo',
      'accommodation_boutique_hotel': 'Hotel boutique',
      'accommodation_business_hotel': 'Hotel de negocios',
      'accommodation_budget_hotel': 'Hotel económico',
      'accommodation_resort': 'Resort',
      'accommodation_riad': 'Riad',
      'accommodation_guesthouse': 'Casa de huéspedes',
      'accommodation_apartment': 'Apartamento',
      'accommodation_villa': 'Villa',
      'group_solo': 'Solo',
      'group_couple': 'En pareja',
      'group_family': 'Con familia',
      'group_friends': 'Con amigos',
      'group_family_kids': 'Familia con niños',
      'group_family_adults': 'Familia con adultos',
      'group_friends_small': 'Pequeño grupo de amigos',
      'group_friends_large': 'Gran grupo de amigos',
      'transportation_flight': 'Vuelo',
      'transportation_car_rental': 'Alquiler de coche',
      'transportation_private_driver': 'Conductor privado',
      'transportation_public_transport': 'Transporte público',
      'transportation_train': 'Tren',
      'transportation_taxi_ride_share': 'Taxi/Compartir viaje',
      'transportation_bicycle': 'Bicicleta',
      'transportation_walking': 'Caminar',
      'activity_culture_history': 'Cultura e Historia',
      'activity_nature_wildlife': 'Naturaleza y Vida Silvestre',
      'activity_beach_water': 'Playa y Actividades Acuáticas',
      'activity_adventure_sports': 'Deportes de Aventura',
      'activity_nightlife_entertainment': 'Vida Nocturna y Entretenimiento',
      'activity_food_gastronomy': 'Comida y Gastronomía',
      'activity_shopping': 'Compras',
      'activity_wellness_spa': 'Bienestar y Spa',
      'duration_unit': 'días',
      'home_title': 'Inicio',
      'home_welcome': 'Bienvenido',
      'guest_ready_to_travel': '¿Listo para comenzar tu viaje?',
      'guest_create_account_description':
          'Crea tu cuenta para guardar tus preferencias y acceder a todas las funciones',
      'guest_login': 'Iniciar sesión',
      'guest_signup': 'Registrarse',
      'guest_unlock_features': 'Desbloquea todas las funciones',
      'guest_edit_profile': 'Edita tu perfil y preferencias',
      'guest_manage_reservations': 'Gestiona tus reservas',
      'guest_save_destinations': 'Guarda tus destinos favoritos',
      'guest_write_reviews': 'Deja reseñas y comentarios',
      'guest_share_photos': 'Comparte tus fotos de viaje',
      'home_search_hint': 'Buscar destinos, actividades...',
      'home_recommendations_title': 'Recomendaciones cerca de ti',
      'rec_park_title': 'Parque Central',
      'rec_park_subtitle': 'Un hermoso parque urbano con lagos y senderos.',
      'rec_museum_title': 'Museo del Louvre',
      'rec_museum_subtitle': 'Explora colecciones de arte famosas en el mundo.',
      'home_trending_title': 'Destinos en tendencia',
      'trending_paris_name': 'París',
      'trending_paris_subtitle': 'La Ciudad de la Luz te espera.',
      'trending_kyoto_name': 'Kioto',
      'trending_kyoto_subtitle': 'Descubre templos y jardines antiguos.',
      'home_seasonal_title': 'Destacados estacionales',
      'seasonal_summer_title': 'Escapadas de verano',
      'seasonal_summer_subtitle': 'Lugares perfectos para el sol y el mar.',
      'seasonal_autumn_title': 'Aventuras de otoño',
      'seasonal_autumn_subtitle':
          'Explora el follaje de otoño y el clima fresco.',
      'home_featured_cities_title': 'Ciudades destacadas',
      'city_nyc_name': 'Nueva York',
      'city_paris_name': 'París',
      'city_tokyo_name': 'Tokio',
      'tag_business': 'Negocios',
      'tag_art_culture': 'Arte y Cultura',
      'tag_museums': 'Museos',
      'tag_cultural_attractions': 'Atracciones culturales',
      'tag_technology': 'Tecnología',
      'tag_traditional_culture': 'Cultura tradicional',
      'reviews_label': 'reseñas',
      'nav_home': 'Inicio',
      'nav_explore': 'Explorar',
      'nav_products': 'Productos',
      'nav_saved': 'Guardado',
      'nav_profile': 'Perfil',
      'explore_title': 'Explora Marruecos',
      'explore_subtitle': 'Descubre destinos y actividades increíbles',
      'products_title': 'Productos Marroquíes',
      'products_subtitle': 'Compra productos artesanales auténticos',
      'saved_title': 'Tus Elementos Guardados',
      'saved_subtitle': 'Lugares, actividades y productos que guardaste',
      'profile_name': 'Nasreddine Bikikre',
      'profile_subtitle': 'Administra tu perfil y preferencias',
      'of': 'de',
      'guest_mode_info': 'Modo invitado - Funciones limitadas',
      'guest_mode_description':
          'Puedes explorar la aplicación, pero algunas funciones requieren inicio de sesión',
      'login_required': 'Inicio de sesión requerido',
      'login_required_message':
          'Esta función requiere inicio de sesión. ¿Te gustaría iniciar sesión ahora?',
      'cancel': 'Cancelar',
      'login': 'Iniciar sesión',
      'plan_your_itinerary': 'Planifica tu Itinerario',
      'trip_duration': 'Duración del Viaje',
      'one_day': '1 Día',
      'two_days': '2 Días',
      'three_days': '3 Días',
      'five_days': '5 Días',
      'days': 'días',
      'budget': 'Presupuesto',
      'budget_range': 'Rango de Presupuesto',
      'low_range': 'Económico',
      'mid_range': 'Medio',
      'high_range': 'Lujo',
      'luxury': 'Lujo',
      'start_date': 'Fecha de Inicio',
      'select_date': 'Seleccionar Fecha',
      'activities': 'Actividades',
      'activities_interests': 'Actividades e Intereses',
      'select_activities': 'Selecciona las actividades que te gustaría incluir',
      'generate_itinerary': 'Generar Itinerario',
      'itinerary_generated': '¡Itinerario Generado!',
      'itinerary_success':
          'Tu itinerario personalizado ha sido creado con éxito.',
      'ok': 'OK',
      'share': 'Compartir',
      'activity_booked_title': '¡Actividad reservada!',
      'activity_booked_success': 'Has reservado con éxito:',
      'season': 'Temporada',
      'all_year': 'Todo el año',
      'share_functionality_coming_soon':
          '¡La función de compartir llegará pronto!',
      'route_not_found': 'Ruta no encontrada',
      'search_title': 'Buscar',
      'search_page_title': 'Página de búsqueda',
      'coming_soon': 'Próximamente...',

      'destination_detail': 'Detalle del destino',
      'detail_page_coming_soon': 'Página de detalles próximamente...',

      'activity_detail': 'Detalle de la actividad',

      'product_detail': 'Detalle del producto',
      'collection': 'Colección',
      'seasonal_collection': 'Colección de temporada',
      'collection_page_coming_soon': 'Página de colección próximamente...',
      'settings': 'Configuración',
      'settings_page_coming_soon': 'Página de configuración próximamente...',
      'help_support': 'Ayuda y Soporte',
      'help_page_coming_soon': 'Página de ayuda próximamente...',
      'error_skipping_questionnaire': 'Error al saltar el cuestionario',
      'error_saving_preferences': 'Error al guardar las preferencias',
      'retry': 'Reintentar',
      'book_now': 'Reservar ahora',
      'added_to_wishlist': 'Añadido a favoritos',
      'removed_from_wishlist': 'Eliminado de favoritos',
      'view_details': 'Ver detalles',
      'error_booking_activity': 'Error al reservar la actividad',
      'city_label_colon': 'Ciudad:',
      'loading_cities': 'Cargando ciudades...',
      'all_cities': 'Todas las ciudades',
      'get_directions': 'Obtener indicaciones',
      'directions_functionality_coming_soon': '¡La función de indicaciones llegará pronto!',
      'phone_hint_example': '+212 6XX XX XX XX',
      'search_cities_countries_activities_hint': 'Buscar ciudades, países o actividades...',
      'otp_hint': '------',
      'activity_sightseeing': 'Turismo',
      'activity_food_tour': 'Tour Gastronómico',
      'activity_cultural_visit': 'Visita Cultural',
      'activity_relaxation': 'Relajación',
      'unknown_destination': 'Destino Desconocido',
      // Filter page translations
      'filters': 'Filtros',
      'clear': 'Limpiar',
      'category': 'Categoría',
      'all': 'Todos',
      'cities': 'Ciudades',
      'culture': 'Cultura',
      'nature': 'Naturaleza',
      'adventure': 'Aventura',
      'beach': 'Playa',
      'desert': 'Desierto',
      'all_budgets': 'Todos los Presupuestos',
      'duration': 'Duración',
      'any_duration': 'Cualquier Duración',
      'weekend': 'Fin de Semana',
      'short_trip': 'Viaje Corto',
      'one_week': 'Una Semana',
      'extended': 'Extendido',
      'experience_type': 'Tipo de Experiencia',
      'apply_filters': 'Aplicar Filtros',
      // Profile page translations
      'profile': 'Perfil',
      'member_since': 'Miembro desde',
      'contribution': 'contribución',
      'contributions': 'contribuciones',
      'tell_about_yourself': 'Cuéntales a otros viajeros un poco sobre ti.',
      'no_city_selected': 'Ninguna ciudad seleccionada.',
      'your_achievements': 'Tus Logros',
      'show_all': 'Mostrar todo',
      'write_first_review': 'Escribe tu primera reseña',
      'unlock_levels_reviews': 'Desbloquea niveles con reseñas',
      'upload_first_photo': 'Sube tu primera foto',
      'unlock_levels_photos': 'Desbloquea niveles con fotos',
      'reservations': 'Reservas',
      'preferences': 'Preferencias',
      'theme': 'Tema',
      'choose_theme': 'Elegir Tema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'system': 'Sistema',
      'always_use_light': 'Siempre usar tema claro',
      'always_use_dark': 'Siempre usar tema oscuro',
      'follow_system_theme': 'Seguir tema del sistema',
      // Edit Profile page translations
      'account_information': 'Información de la Cuenta',
      'first_name': 'Nombre',
      'last_name': 'Apellido',
      'enter_first_name': 'Ingresa tu nombre',
      'enter_last_name': 'Ingresa tu apellido',
      'home_airport': 'Aeropuerto de Origen',
      'airport_hint': 'Ingresa el código de tu aeropuerto de origen',
      'enter_email': 'Ingresa tu dirección de correo electrónico',
      'full_address': 'Dirección Completa',
      'enter_address': 'Ingresa tu dirección completa',
      'address_suite': 'Dirección/Suite',
      'additional_address_info': 'Información de dirección adicional',
      'city': 'Ciudad',
      'enter_city': 'Ingresa tu ciudad',
      'state_region_province': 'Estado/Región/Provincia',
      'enter_region': 'Ingresa tu región',
      'postal_code': 'Código Postal',
      'enter_postal_code': 'Ingresa tu código postal',
      'country': 'País',
      'select_country': 'Selecciona tu país',
      'france': 'Francia',
      'spain': 'España',
      'usa': 'Estados Unidos',
      'phone_number': 'Número de Teléfono',
      'renew_password': 'Renovar Contraseña',
      'save': 'Guardar',
      'profile_updated_success': '¡Perfil actualizado con éxito!',
      'field_required': 'Este campo es requerido',
      'choose_from_gallery': 'Elegir de la Galería',
      'take_photo': 'Tomar Foto',
      // Wishlist/Saved page translations
      'products': 'Productos',
      'no_activities_saved': 'No hay actividades guardadas aún',
      'start_exploring_activities':
          'Comienza a explorar y guarda tus actividades favoritas',
      'explore_activities': 'Explorar Actividades',
      'no_cities_saved': 'No hay ciudades guardadas aún',
      'save_cities_visit': 'Guarda las ciudades que quieres visitar',
      'explore_cities': 'Explorar Ciudades',
      'no_products_saved': 'No hay productos guardados aún',
      'save_products_buy': 'Guarda los productos que quieres comprar',
      'explore_products': 'Explorar Productos',
      'activity': 'Actividad',
      'location': 'Ubicación',
      'price': 'Precio',
      // Explore page translations
      'explore_morocco': 'Explorar Marruecos',
      'search_cities_activities': 'Buscar ciudades, actividades...',
      'categories': 'Categorías',
      'popular_cities': 'Ciudades Populares',
      'recommended_activities': 'Actividades Recomendadas',
      'upcoming_events': 'Próximos Eventos',
      'view_all': 'Ver Todo',
      'marrakech': 'Marrakech',
      'fes': 'Fez',
      'chefchaouen': 'Chefchaouen',
      'sahara_desert_safari': 'Safari en el Desierto del Sahara',
      'marrakech_medina_tour': 'Tour de la Medina de Marrakech',
      'moroccan_cooking_class': 'Clase de Cocina Marroquí',
      'cinema_world_music_festival': 'Festival de Música del Mundo',
      'rose_festival': 'Festival de las Rosas',
      'essaouira': 'Essaouira',
      'kelaat_mgouna': 'Kelaat M\'Gouna',
      'june_10_15': '10-15 Junio',
      'may_10_12': '10-12 Mayo',

      // Products page translations
      '2_4_hours': '2-4 horas',
      '3_4_hours': '3-4 horas',
      '2_3_hours': '2-3 horas',
      '1_2_hours': '1-2 horas',
      '4_6_hours': '4-6 horas',
      // Search page translations
      'search_morocco': 'Buscar Marruecos',
      'search_cities_activities_hint': 'Buscar ciudades, actividades...',
      'search_for_cities_activities':
          'Busca ciudades, actividades o atracciones',
      'no_results_found': 'No se encontraron resultados para',
      'try_different_keywords':
          'Intenta diferentes palabras clave o verifica la ortografía',
      // Details page translations
      'key_attractions': 'Atracciones Principales',

      'location_on_map': 'Ubicación en el Mapa',
      'map_view': 'Vista de Mapa',
      'explore_the_souks': 'Explorar los Zocos',
      'visit_secret_garden': 'Visitar el Jardín Secreto',
      'enjoy_traditional_hammam': 'Disfrutar de un Hammam Tradicional',
      'hot_air_balloon_ride': 'Paseo en Globo Aerostático',
      'various_locations': 'Diversas ubicaciones',
      'medina': 'Medina',
      'palmerale': 'Palmeral',
      // Enhanced Welcome Screen translations
      'choose_your_city': 'Elige tu ciudad',
      'detecting_location': 'Detectando tu ubicación...',
      'selected_city_info': 'Información de la ciudad',
      // Preferences page translations
      'language': 'Idioma',
      // Reservations page translations
      'no_reservations_yet': '¿Aún no tienes reservas? ¡Vamos a solucionarlo!',
      'book_before_you_go':
          'Reserva antes de ir para descubrir lo mejor en el sitio.',
      'start_planning': 'Comenzar a planificar',
      'new_trip': 'Nuevo Viaje',
      'explore': 'Explorar',
      'logout': 'Cerrar Sesión',
      // Wishlist translations
      'wishlist': 'Lista de deseos',
      'currency': 'Moneda',
      'payment_method': 'Método de pago',
      'card_number': 'Número de tarjeta',
      'expiry': 'Vencimiento',
      'cvc': 'CVC',
      'cardholder_name': 'Nombre del titular',
      'name_on_card': 'Nombre en la tarjeta',
      'payment_info_saved': '¡Información de pago guardada!',
      'euro': 'Euro',
      'mad': 'Dirham marroquí',
      'dollar': 'Dólar estadounidense',
      // Trip management translations
      'Trips': 'Viajes',
      'create_trip': 'Crear Viaje',
      'edit_trip': 'Editar Viaje',
      'trip_details': 'Detalles del Viaje',
      'trip_name': 'Nombre del Viaje',
      'trip_name_required': 'El nombre del viaje es obligatorio',
      'destination': 'Destino',
      'destination_required': 'El destino es obligatorio',
      'end_date': 'Fecha de Fin',
      'notes': 'Notas',
      'add_activity': 'Agregar Actividad',
      'no_activities_added': 'No se han agregado actividades aún',
      'add_activities_description':
          'Toca los botones de arriba para agregar actividades a tu viaje',
      'save_changes': 'Guardar Cambios',
      'create_your_first_trip':
          'Crea tu primer viaje y comienza a planificar tu aventura',
      'no_trips_saved': 'No hay viajes guardados aún',
      'created': 'Creado',
      // Carrito y Pago
      'shopping_cart': 'Carrito de compras',
      'failed_load_cart_items': 'Error al cargar los artículos del carrito',
      'cart_empty_title': 'Tu carrito está vacío',
      'cart_empty_subtitle': '¡Agrega algunos productos para comenzar!',
      'continue_shopping': 'Continuar comprando',
      'total': 'Total:',
      'proceed_to_checkout': 'Proceder al pago',
      'checkout': 'Pago',
      'place_order': 'Realizar pedido',
      'order_summary': 'Resumen del pedido',
      'qty': 'Cant.',
      'shipping_information': 'Información de envío',
      'enter_full_name': 'Por favor ingresa tu nombre completo',
      'enter_valid_email': 'Por favor ingresa un correo válido',
      'enter_phone_number': 'Por favor ingresa tu número de teléfono',

      'credit_card': 'Tarjeta de crédito',
      'pay_with_credit_card': 'Pagar con tu tarjeta de crédito',
      'pay_with_paypal': 'Pagar con tu cuenta de PayPal',
      'cash_on_delivery': 'Pago contra entrega',
      'pay_on_delivery': 'Paga cuando llegue tu pedido',
    },
  };
}
