class MoroccanAccommodationsService {
  static final MoroccanAccommodationsService _instance =
      MoroccanAccommodationsService._internal();
  factory MoroccanAccommodationsService() => _instance;
  MoroccanAccommodationsService._internal();

  // Hébergements par ville avec détails complets
  Map<String, List<Map<String, dynamic>>> get accommodationsByCity => {
    'Casablanca': [
      {
        'id': 1,
        'nom': 'Hotel Casablanca',
        'type': 'Hôtel 5 étoiles',
        'description':
            'Hôtel de luxe au cœur de Casablanca avec vue sur la mosquée Hassan II. Confort moderne et service exceptionnel.',
        'adresse': 'Boulevard de la Corniche, Casablanca',
        'prix': 1200,
        'prixMin': 800,
        'prixMax': 2000,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/casablanca_art_gallery.jpg',
        'latitude': 33.6084,
        'longitude': -7.6328,
        'ville': 'Casablanca',
        'categorie': 'Hôtel de luxe',
        'equipements': [
          'WiFi',
          'Piscine',
          'Spa',
          'Restaurant',
          'Parking',
          'Gym',
        ],
        'services': [
          'Room service',
          'Concierge',
          'Blanchisserie',
          'Navette aéroport',
        ],
        'disponibilite': true,
        'chambresDisponibles': 15,
        'checkIn': '15:00',
        'checkOut': '12:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 24h avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Excellent emplacement près des attractions principales',
      },
      {
        'id': 2,
        'nom': 'Riad Dar Bensouda',
        'type': 'Riad traditionnel',
        'description':
            'Riad authentique dans la médina de Casablanca, alliant tradition marocaine et confort moderne.',
        'adresse': 'Rue des Consuls, Médina, Casablanca',
        'prix': 450,
        'prixMin': 350,
        'prixMax': 650,
        'devise': 'MAD',
        'notesMoyennes': 4.5,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 33.5728,
        'longitude': -7.5895,
        'ville': 'Casablanca',
        'categorie': 'Riad',
        'equipements': ['WiFi', 'Terrasse', 'Jardin', 'Cuisine marocaine'],
        'services': ['Petit-déjeuner', 'Excursions', 'Massage traditionnel'],
        'disponibilite': true,
        'chambresDisponibles': 8,
        'checkIn': '14:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 48h avant',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Expérience authentique dans la médina',
      },
      {
        'id': 3,
        'nom': 'Appartement Corniche',
        'type': 'Appartement',
        'description':
            'Appartement moderne avec vue sur l\'océan, idéal pour un séjour prolongé à Casablanca.',
        'adresse': 'Avenue de la Corniche, Casablanca',
        'prix': 300,
        'prixMin': 250,
        'prixMax': 400,
        'devise': 'MAD',
        'notesMoyennes': 4.3,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 33.6100,
        'longitude': -7.6300,
        'ville': 'Casablanca',
        'categorie': 'Appartement',
        'equipements': ['WiFi', 'Cuisine équipée', 'Balcon', 'Climatisation'],
        'services': ['Ménage', 'Réception 24h/24'],
        'disponibilite': true,
        'chambresDisponibles': 1,
        'checkIn': '15:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 7 jours avant',
        'langues': ['Français', 'Anglais'],
        'note': 'Parfait pour les familles et séjours longs',
      },
    ],
    'Marrakech': [
      {
        'id': 4,
        'nom': 'La Mamounia',
        'type': 'Palace 5 étoiles',
        'description':
            'Palace légendaire de Marrakech, symbole du luxe marocain avec ses jardins historiques et son spa exceptionnel.',
        'adresse': 'Avenue Bab Jdid, Marrakech',
        'prix': 2500,
        'prixMin': 2000,
        'prixMax': 5000,
        'devise': 'MAD',
        'notesMoyennes': 4.9,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 31.6258,
        'longitude': -7.9891,
        'ville': 'Marrakech',
        'categorie': 'Palace',
        'equipements': [
          'WiFi',
          'Piscine',
          'Spa',
          'Golf',
          'Restaurants',
          'Parking',
          'Gym',
        ],
        'services': [
          'Butler',
          'Concierge',
          'Room service',
          'Blanchisserie',
          'Navette',
        ],
        'disponibilite': true,
        'chambresDisponibles': 5,
        'checkIn': '15:00',
        'checkOut': '12:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 24h avant',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol'],
        'note': 'Expérience de luxe incomparable au cœur de Marrakech',
      },
      {
        'id': 5,
        'nom': 'Riad Yasmine',
        'type': 'Riad boutique',
        'description':
            'Riad intime et élégant dans la médina, offrant une expérience authentique avec un service personnalisé.',
        'adresse': 'Derb Aarjane, Médina, Marrakech',
        'prix': 650,
        'prixMin': 500,
        'prixMax': 900,
        'devise': 'MAD',
        'notesMoyennes': 4.8,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 31.6300,
        'longitude': -7.9800,
        'ville': 'Marrakech',
        'categorie': 'Riad',
        'equipements': ['WiFi', 'Piscine', 'Terrasse', 'Jardin', 'Spa'],
        'services': [
          'Petit-déjeuner',
          'Dîner traditionnel',
          'Excursions',
          'Massage',
        ],
        'disponibilite': true,
        'chambresDisponibles': 6,
        'checkIn': '14:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 48h avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Oasis de paix dans la médina animée',
      },
      {
        'id': 6,
        'nom': 'Villa Palmeraie',
        'type': 'Villa de luxe',
        'description':
            'Villa privée dans la palmeraie de Marrakech avec piscine privée et jardin, idéale pour groupes et familles.',
        'adresse': 'Palmeraie, Marrakech',
        'prix': 1800,
        'prixMin': 1500,
        'prixMax': 2500,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 31.7000,
        'longitude': -7.9500,
        'ville': 'Marrakech',
        'categorie': 'Villa',
        'equipements': [
          'WiFi',
          'Piscine privée',
          'Jardin',
          'Cuisine',
          'Parking',
        ],
        'services': ['Chef privé', 'Ménage', 'Garde', 'Navette'],
        'disponibilite': true,
        'chambresDisponibles': 1,
        'checkIn': '15:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 7 jours avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Retraite privée dans la palmeraie',
      },
    ],
    'Rabat': [
      {
        'id': 7,
        'nom': 'Hotel Rabat',
        'type': 'Hôtel 4 étoiles',
        'description':
            'Hôtel moderne au centre de Rabat, proche des institutions gouvernementales et des sites historiques.',
        'adresse': 'Avenue Allal Ben Abdellah, Rabat',
        'prix': 800,
        'prixMin': 600,
        'prixMax': 1200,
        'devise': 'MAD',
        'notesMoyennes': 4.4,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'longitude': -6.8416,
        'ville': 'Rabat',
        'categorie': 'Hôtel business',
        'equipements': [
          'WiFi',
          'Salle de conférence',
          'Restaurant',
          'Parking',
          'Gym',
        ],
        'services': ['Room service', 'Blanchisserie', 'Navette aéroport'],
        'disponibilite': true,
        'chambresDisponibles': 20,
        'checkIn': '15:00',
        'checkOut': '12:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 24h avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Idéal pour les voyages d\'affaires',
      },
      {
        'id': 8,
        'nom': 'Riad Dar Soukaina',
        'type': 'Riad traditionnel',
        'description':
            'Riad authentique dans la médina de Rabat, alliant charme traditionnel et confort moderne.',
        'adresse': 'Rue des Consuls, Médina, Rabat',
        'prix': 400,
        'prixMin': 300,
        'prixMax': 550,
        'devise': 'MAD',
        'notesMoyennes': 4.2,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 34.0250,
        'longitude': -6.8350,
        'ville': 'Rabat',
        'categorie': 'Riad',
        'equipements': ['WiFi', 'Terrasse', 'Jardin', 'Cuisine marocaine'],
        'services': ['Petit-déjeuner', 'Excursions', 'Cours de cuisine'],
        'disponibilite': true,
        'chambresDisponibles': 5,
        'checkIn': '14:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 48h avant',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Charme authentique de la médina',
      },
    ],
    'Fès': [
      {
        'id': 9,
        'nom': 'Palais Faraj',
        'type': 'Palace 5 étoiles',
        'description':
            'Palace historique dans la médina de Fès, offrant une expérience de luxe dans un cadre patrimonial exceptionnel.',
        'adresse': 'Médina, Fès',
        'prix': 1500,
        'prixMin': 1200,
        'prixMax': 2500,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 34.0522,
        'longitude': -4.9828,
        'ville': 'Fès',
        'categorie': 'Palace',
        'equipements': ['WiFi', 'Spa', 'Restaurant', 'Terrasse', 'Parking'],
        'services': [
          'Butler',
          'Concierge',
          'Excursions culturelles',
          'Cours d\'artisanat',
        ],
        'disponibilite': true,
        'chambresDisponibles': 8,
        'checkIn': '15:00',
        'checkOut': '12:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 24h avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Immersion dans l\'histoire de Fès',
      },
      {
        'id': 10,
        'nom': 'Riad Fès',
        'type': 'Riad traditionnel',
        'description':
            'Riad authentique au cœur de la médina de Fès, témoin de l\'architecture traditionnelle marocaine.',
        'adresse': 'Derb Zerbtana, Médina, Fès',
        'prix': 350,
        'prixMin': 250,
        'prixMax': 500,
        'devise': 'MAD',
        'notesMoyennes': 4.3,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 34.0550,
        'longitude': -4.9800,
        'ville': 'Fès',
        'categorie': 'Riad',
        'equipements': ['WiFi', 'Terrasse', 'Jardin', 'Cuisine traditionnelle'],
        'services': [
          'Petit-déjeuner',
          'Visites guidées',
          'Ateliers artisanaux',
        ],
        'disponibilite': true,
        'chambresDisponibles': 4,
        'checkIn': '14:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 48h avant',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Authenticité et tradition à Fès',
      },
    ],
    'Agadir': [
      {
        'id': 11,
        'nom': 'Hotel Agadir Beach Club',
        'type': 'Hôtel 5 étoiles',
        'description':
            'Complexe hôtelier de luxe sur la plage d\'Agadir avec vue panoramique sur l\'océan Atlantique.',
        'adresse': 'Boulevard de la Corniche, Agadir',
        'prix': 1000,
        'prixMin': 800,
        'prixMax': 1500,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 30.4278,
        'longitude': -9.5981,
        'ville': 'Agadir',
        'categorie': 'Hôtel de plage',
        'equipements': [
          'WiFi',
          'Piscine',
          'Spa',
          'Restaurant',
          'Parking',
          'Gym',
          'Plage privée',
        ],
        'services': [
          'Room service',
          'Sports nautiques',
          'Excursions',
          'Blanchisserie',
        ],
        'disponibilite': true,
        'chambresDisponibles': 25,
        'checkIn': '15:00',
        'checkOut': '12:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 24h avant',
        'langues': ['Français', 'Anglais', 'Arabe', 'Allemand'],
        'note': 'Parfait pour les vacances en bord de mer',
      },
      {
        'id': 12,
        'nom': 'Riad Villa Blanche',
        'type': 'Riad moderne',
        'description':
            'Riad contemporain alliant design moderne et tradition marocaine, proche de la plage d\'Agadir.',
        'adresse': 'Quartier Talborjt, Agadir',
        'prix': 500,
        'prixMin': 400,
        'prixMax': 700,
        'devise': 'MAD',
        'notesMoyennes': 4.4,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 30.4300,
        'longitude': -9.6000,
        'ville': 'Agadir',
        'categorie': 'Riad',
        'equipements': ['WiFi', 'Piscine', 'Terrasse', 'Jardin', 'Cuisine'],
        'services': [
          'Petit-déjeuner',
          'Navette plage',
          'Excursions',
          'Massage',
        ],
        'disponibilite': true,
        'chambresDisponibles': 6,
        'checkIn': '14:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 48h avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Design moderne et confort à Agadir',
      },
    ],
    'Tanger': [
      {
        'id': 13,
        'nom': 'Hotel Continental',
        'type': 'Hôtel historique 4 étoiles',
        'description':
            'Hôtel historique de Tanger avec vue sur le détroit de Gibraltar, chargé d\'histoire et de charme.',
        'adresse': 'Place de France, Tanger',
        'prix': 600,
        'prixMin': 450,
        'prixMax': 900,
        'devise': 'MAD',
        'notesMoyennes': 4.2,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 35.7595,
        'longitude': -5.8339,
        'ville': 'Tanger',
        'categorie': 'Hôtel historique',
        'equipements': ['WiFi', 'Restaurant', 'Bar', 'Terrasse', 'Parking'],
        'services': ['Room service', 'Excursions', 'Blanchisserie'],
        'disponibilite': true,
        'chambresDisponibles': 12,
        'checkIn': '15:00',
        'checkOut': '12:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 24h avant',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol'],
        'note': 'Histoire et charme au cœur de Tanger',
      },
      {
        'id': 14,
        'nom': 'Appartement Marina',
        'type': 'Appartement moderne',
        'description':
            'Appartement moderne avec vue sur le port de Tanger, idéal pour découvrir la ville et ses environs.',
        'adresse': 'Marina de Tanger',
        'prix': 350,
        'prixMin': 280,
        'prixMax': 450,
        'devise': 'MAD',
        'notesMoyennes': 4.1,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 35.7600,
        'longitude': -5.8300,
        'ville': 'Tanger',
        'categorie': 'Appartement',
        'equipements': ['WiFi', 'Cuisine équipée', 'Balcon', 'Climatisation'],
        'services': ['Ménage', 'Réception 24h/24'],
        'disponibilite': true,
        'chambresDisponibles': 1,
        'checkIn': '15:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 7 jours avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Vue imprenable sur le port de Tanger',
      },
    ],
    'Chefchaouen': [
      {
        'id': 15,
        'nom': 'Riad Lina',
        'type': 'Riad traditionnel',
        'description':
            'Riad authentique dans la médina bleue de Chefchaouen, offrant une expérience unique dans cette ville emblématique.',
        'adresse': 'Médina, Chefchaouen',
        'prix': 300,
        'prixMin': 200,
        'prixMax': 450,
        'devise': 'MAD',
        'notesMoyennes': 4.5,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 35.1714,
        'longitude': -5.2696,
        'ville': 'Chefchaouen',
        'categorie': 'Riad',
        'equipements': ['WiFi', 'Terrasse', 'Jardin', 'Cuisine marocaine'],
        'services': [
          'Petit-déjeuner',
          'Excursions montagne',
          'Cours de cuisine',
        ],
        'disponibilite': true,
        'chambresDisponibles': 5,
        'checkIn': '14:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 48h avant',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Immersion dans la ville bleue',
      },
    ],
    'Essaouira': [
      {
        'id': 16,
        'nom': 'Hotel des Iles',
        'type': 'Hôtel 4 étoiles',
        'description':
            'Hôtel de charme face à l\'océan à Essaouira, parfait pour les amateurs de surf et de culture.',
        'adresse': 'Boulevard Mohammed V, Essaouira',
        'prix': 700,
        'prixMin': 550,
        'prixMax': 1000,
        'devise': 'MAD',
        'notesMoyennes': 4.3,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 31.5085,
        'longitude': -9.7595,
        'ville': 'Essaouira',
        'categorie': 'Hôtel de charme',
        'equipements': ['WiFi', 'Restaurant', 'Bar', 'Terrasse', 'Parking'],
        'services': [
          'Room service',
          'Sports nautiques',
          'Excursions',
          'Blanchisserie',
        ],
        'disponibilite': true,
        'chambresDisponibles': 15,
        'checkIn': '15:00',
        'checkOut': '12:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 24h avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Charme et culture à Essaouira',
      },
      {
        'id': 17,
        'nom': 'Riad Dar Maya',
        'type': 'Riad boutique',
        'description':
            'Riad intime dans la médina d\'Essaouira, alliant art et tradition dans un cadre unique.',
        'adresse': 'Rue de la Skala, Médina, Essaouira',
        'prix': 400,
        'prixMin': 300,
        'prixMax': 600,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 31.5100,
        'longitude': -9.7600,
        'ville': 'Essaouira',
        'categorie': 'Riad',
        'equipements': ['WiFi', 'Terrasse', 'Jardin', 'Spa', 'Cuisine'],
        'services': [
          'Petit-déjeuner',
          'Ateliers d\'art',
          'Excursions',
          'Massage',
        ],
        'disponibilite': true,
        'chambresDisponibles': 4,
        'checkIn': '14:00',
        'checkOut': '11:00',
        'politiqueAnnulation': 'Gratuite jusqu\'à 48h avant',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Art et tradition à Essaouira',
      },
    ],
  };

  // Obtenir les hébergements par ville
  List<Map<String, dynamic>> getAccommodationsByCity(String cityName) {
    return accommodationsByCity[cityName] ?? [];
  }

  // Obtenir tous les hébergements
  List<Map<String, dynamic>> getAllAccommodations() {
    List<Map<String, dynamic>> allAccommodations = [];
    accommodationsByCity.values.forEach((accommodations) {
      allAccommodations.addAll(accommodations);
    });
    return allAccommodations;
  }

  // Rechercher des hébergements
  List<Map<String, dynamic>> searchAccommodations(String query) {
    final allAccommodations = getAllAccommodations();
    return allAccommodations.where((accommodation) {
      final name = accommodation['nom']?.toString().toLowerCase() ?? '';
      final type = accommodation['type']?.toString().toLowerCase() ?? '';
      final description =
          accommodation['description']?.toString().toLowerCase() ?? '';
      final city = accommodation['ville']?.toString().toLowerCase() ?? '';
      final searchQuery = query.toLowerCase();

      return name.contains(searchQuery) ||
          type.contains(searchQuery) ||
          description.contains(searchQuery) ||
          city.contains(searchQuery);
    }).toList();
  }

  // Obtenir les types d'hébergements disponibles
  List<String> getAccommodationTypes() {
    return [
      'Hôtel de luxe',
      'Hôtel 5 étoiles',
      'Hôtel 4 étoiles',
      'Hôtel de charme',
      'Hôtel business',
      'Hôtel de plage',
      'Hôtel historique',
      'Palace',
      'Riad',
      'Riad traditionnel',
      'Riad boutique',
      'Riad moderne',
      'Appartement',
      'Villa',
      'Villa de luxe',
    ];
  }

  // Obtenir les équipements disponibles
  List<String> getAvailableEquipments() {
    return [
      'WiFi',
      'Piscine',
      'Spa',
      'Restaurant',
      'Parking',
      'Gym',
      'Terrasse',
      'Jardin',
      'Cuisine équipée',
      'Balcon',
      'Climatisation',
      'Plage privée',
      'Salle de conférence',
      'Bar',
      'Golf',
    ];
  }
}
