class MoroccanServicesService {
  static final MoroccanServicesService _instance =
      MoroccanServicesService._internal();
  factory MoroccanServicesService() => _instance;
  MoroccanServicesService._internal();

  // Services par ville avec détails complets
  Map<String, List<Map<String, dynamic>>> get servicesByCity => {
    'Casablanca': [
      {
        'id': 1,
        'nom': 'Spa & Wellness Center',
        'type': 'Spa et bien-être',
        'description':
            'Centre de spa moderne offrant des soins traditionnels marocains et des traitements de luxe dans un cadre relaxant.',
        'adresse': 'Boulevard de la Corniche, Casablanca',
        'prix': 300,
        'prixMin': 200,
        'prixMax': 500,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/casablanca_art_gallery.jpg',
        'latitude': 33.6084,
        'longitude': -7.6328,
        'ville': 'Casablanca',
        'categorie': 'Bien-être',
        'equipements': [
          'Hammam',
          'Massage',
          'Sauna',
          'Piscine',
          'Salle de fitness',
        ],
        'services': [
          'Massage traditionnel',
          'Soins du visage',
          'Rituel hammam',
          'Yoga',
        ],
        'horaires': '9h00 - 22h00',
        'telephone': '+212 5 22 12 34 56',
        'email': 'spa@casablanca-wellness.ma',
        'siteWeb': 'www.casablanca-wellness.ma',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Expérience de détente exceptionnelle au cœur de Casablanca',
      },
      {
        'id': 2,
        'nom': 'Guided City Tours',
        'type': 'Visites guidées',
        'description':
            'Visites guidées professionnelles de Casablanca avec guides locaux expérimentés parlant plusieurs langues.',
        'adresse': 'Place Mohammed V, Casablanca',
        'prix': 150,
        'prixMin': 100,
        'prixMax': 250,
        'devise': 'MAD',
        'notesMoyennes': 4.8,
        'imageUrl': 'assets/images/activities/casablanca_business.jpg',
        'latitude': 33.5731,
        'longitude': -7.5898,
        'ville': 'Casablanca',
        'categorie': 'Tourisme',
        'equipements': ['Transport', 'Guide professionnel', 'Audio-guides'],
        'services': [
          'Visite de la mosquée Hassan II',
          'Découverte de l\'Art Déco',
          'Marché central',
          'Quartier des Habous',
        ],
        'horaires': '8h00 - 18h00',
        'telephone': '+212 5 22 23 45 67',
        'email': 'tours@casablanca-guide.ma',
        'siteWeb': 'www.casablanca-guide.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol'],
        'note': 'Découvrez Casablanca avec des guides passionnés',
      },
      {
        'id': 3,
        'nom': 'Restaurant Gastronomique',
        'type': 'Restaurant',
        'description':
            'Restaurant gastronomique proposant une cuisine marocaine raffinée et des spécialités internationales.',
        'adresse': 'Avenue des FAR, Casablanca',
        'prix': 400,
        'prixMin': 300,
        'prixMax': 600,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/casablanca_restaurants.jpg',
        'latitude': 33.5800,
        'longitude': -7.6000,
        'ville': 'Casablanca',
        'categorie': 'Restauration',
        'equipements': ['Terrasse', 'Salle privée', 'Bar', 'Parking'],
        'services': [
          'Cuisine marocaine',
          'Menu dégustation',
          'Service traiteur',
          'Événements privés',
        ],
        'horaires': '12h00 - 15h00, 19h00 - 23h00',
        'telephone': '+212 5 22 34 56 78',
        'email': 'reservation@restaurant-casa.ma',
        'siteWeb': 'www.restaurant-casa.ma',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Expérience culinaire exceptionnelle à Casablanca',
      },
    ],
    'Marrakech': [
      {
        'id': 4,
        'nom': 'Hammam Traditionnel',
        'type': 'Hammam',
        'description':
            'Hammam traditionnel authentique dans la médina de Marrakech, offrant des soins ancestraux et des rituels de purification.',
        'adresse': 'Rue Riad Zitoun el-Jedid, Médina, Marrakech',
        'prix': 200,
        'prixMin': 150,
        'prixMax': 350,
        'devise': 'MAD',
        'notesMoyennes': 4.9,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 31.6258,
        'longitude': -7.9891,
        'ville': 'Marrakech',
        'categorie': 'Bien-être traditionnel',
        'equipements': [
          'Salle de hammam',
          'Massage',
          'Savon noir',
          'Gant de kessa',
        ],
        'services': [
          'Rituel hammam complet',
          'Gommage au savon noir',
          'Massage aux huiles',
          'Thé à la menthe',
        ],
        'horaires': '8h00 - 20h00',
        'telephone': '+212 5 24 12 34 56',
        'email': 'hammam@marrakech-tradition.ma',
        'siteWeb': 'www.marrakech-tradition.ma',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Expérience authentique du hammam marocain',
      },
      {
        'id': 5,
        'nom': 'Atelier d\'Artisanat',
        'type': 'Artisanat',
        'description':
            'Atelier d\'artisanat traditionnel où vous pouvez apprendre les techniques ancestrales de la poterie, du tissage et de la maroquinerie.',
        'adresse': 'Quartier des tanneurs, Médina, Marrakech',
        'prix': 100,
        'prixMin': 80,
        'prixMax': 150,
        'devise': 'MAD',
        'notesMoyennes': 4.5,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 31.6300,
        'longitude': -7.9800,
        'ville': 'Marrakech',
        'categorie': 'Artisanat',
        'equipements': [
          'Atelier équipé',
          'Matériaux fournis',
          'Outils traditionnels',
        ],
        'services': [
          'Cours de poterie',
          'Tissage de tapis',
          'Maroquinerie',
          'Vente d\'artisanat',
        ],
        'horaires': '9h00 - 17h00',
        'telephone': '+212 5 24 23 45 67',
        'email': 'atelier@artisanat-marrakech.ma',
        'siteWeb': 'www.artisanat-marrakech.ma',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Découvrez l\'artisanat marocain authentique',
      },
      {
        'id': 6,
        'nom': 'Transport Privé',
        'type': 'Transport',
        'description':
            'Service de transport privé avec chauffeurs professionnels pour visites et excursions dans Marrakech et ses environs.',
        'adresse': 'Avenue Mohammed VI, Marrakech',
        'prix': 300,
        'prixMin': 250,
        'prixMax': 500,
        'devise': 'MAD',
        'notesMoyennes': 4.4,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 31.6200,
        'longitude': -7.9900,
        'ville': 'Marrakech',
        'categorie': 'Transport',
        'equipements': [
          'Véhicules climatisés',
          'WiFi',
          'Eau minérale',
          'Guide chauffeur',
        ],
        'services': [
          'Transfert aéroport',
          'Visites guidées',
          'Excursions',
          'Service 24h/24',
        ],
        'horaires': '24h/24',
        'telephone': '+212 5 24 34 56 78',
        'email': 'transport@marrakech-mobile.ma',
        'siteWeb': 'www.marrakech-mobile.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol'],
        'note': 'Transport confortable et fiable à Marrakech',
      },
    ],
    'Rabat': [
      {
        'id': 7,
        'nom': 'Service de Traduction',
        'type': 'Traduction',
        'description':
            'Service professionnel de traduction et d\'interprétation pour les visiteurs et les entreprises à Rabat.',
        'adresse': 'Avenue Allal Ben Abdellah, Rabat',
        'prix': 200,
        'prixMin': 150,
        'prixMax': 300,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 34.0209,
        'longitude': -6.8416,
        'ville': 'Rabat',
        'categorie': 'Services professionnels',
        'equipements': ['Bureau équipé', 'Ordinateurs', 'Imprimante', 'WiFi'],
        'services': [
          'Traduction documentaire',
          'Interprétation simultanée',
          'Services notariaux',
          'Conseil juridique',
        ],
        'horaires': '8h00 - 18h00',
        'telephone': '+212 5 37 12 34 56',
        'email': 'traduction@rabat-services.ma',
        'siteWeb': 'www.rabat-services.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol', 'Allemand'],
        'note': 'Services de traduction professionnels à Rabat',
      },
      {
        'id': 8,
        'nom': 'Centre de Conférences',
        'type': 'Événementiel',
        'description':
            'Centre moderne de conférences et d\'événements avec salles équipées et services professionnels.',
        'adresse': 'Boulevard Zerktouni, Rabat',
        'prix': 2000,
        'prixMin': 1500,
        'prixMax': 5000,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 34.0250,
        'longitude': -6.8350,
        'ville': 'Rabat',
        'categorie': 'Événementiel',
        'equipements': [
          'Salles de conférence',
          'Équipement audiovisuel',
          'Catering',
          'Parking',
        ],
        'services': [
          'Organisation d\'événements',
          'Catering',
          'Technique audiovisuelle',
          'Accueil',
        ],
        'horaires': '8h00 - 22h00',
        'telephone': '+212 5 37 23 45 67',
        'email': 'conferences@rabat-centre.ma',
        'siteWeb': 'www.rabat-centre.ma',
        'langues': ['Français', 'Anglais', 'Arabe'],
        'note': 'Événements professionnels de qualité à Rabat',
      },
    ],
    'Fès': [
      {
        'id': 9,
        'nom': 'Guide Médina Fès',
        'type': 'Guide touristique',
        'description':
            'Guides spécialisés de la médina de Fès, classée patrimoine mondial UNESCO, avec expertise historique et culturelle.',
        'adresse': 'Place R\'cif, Médina, Fès',
        'prix': 200,
        'prixMin': 150,
        'prixMax': 300,
        'devise': 'MAD',
        'notesMoyennes': 4.8,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 34.0522,
        'longitude': -4.9828,
        'ville': 'Fès',
        'categorie': 'Tourisme culturel',
        'equipements': ['Audio-guides', 'Cartes', 'Livres historiques'],
        'services': [
          'Visite de la médina',
          'Découverte des souks',
          'Histoire de Fès',
          'Artisanat traditionnel',
        ],
        'horaires': '8h00 - 18h00',
        'telephone': '+212 5 35 12 34 56',
        'email': 'guide@fes-medina.ma',
        'siteWeb': 'www.fes-medina.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol'],
        'note': 'Découvrez l\'histoire millénaire de Fès',
      },
      {
        'id': 10,
        'nom': 'Atelier de Poterie',
        'type': 'Artisanat',
        'description':
            'Atelier traditionnel de poterie où vous pouvez créer vos propres pièces en céramique selon les techniques ancestrales.',
        'adresse': 'Quartier des potiers, Fès',
        'prix': 80,
        'prixMin': 60,
        'prixMax': 120,
        'devise': 'MAD',
        'notesMoyennes': 4.4,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 34.0550,
        'longitude': -4.9800,
        'ville': 'Fès',
        'categorie': 'Artisanat',
        'equipements': [
          'Tours de potier',
          'Four traditionnel',
          'Matériaux',
          'Outils',
        ],
        'services': [
          'Cours de poterie',
          'Cuisson traditionnelle',
          'Décoration',
          'Vente de créations',
        ],
        'horaires': '9h00 - 17h00',
        'telephone': '+212 5 35 23 45 67',
        'email': 'poterie@fes-artisanat.ma',
        'siteWeb': 'www.fes-artisanat.ma',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Créez votre propre poterie à Fès',
      },
    ],
    'Agadir': [
      {
        'id': 11,
        'nom': 'École de Surf',
        'type': 'Sports nautiques',
        'description':
            'École de surf professionnelle avec moniteurs certifiés pour tous niveaux, de débutant à expert.',
        'adresse': 'Plage d\'Agadir, Agadir',
        'prix': 200,
        'prixMin': 150,
        'prixMax': 300,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'longitude': -9.5981,
        'ville': 'Agadir',
        'categorie': 'Sports',
        'equipements': ['Planches de surf', 'Combinaisons', 'Leash', 'Wax'],
        'services': [
          'Cours de surf',
          'Location matériel',
          'Compétitions',
          'Sorties en mer',
        ],
        'horaires': '8h00 - 18h00',
        'telephone': '+212 5 28 12 34 56',
        'email': 'surf@agadir-sports.ma',
        'siteWeb': 'www.agadir-sports.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Allemand'],
        'note': 'Apprenez le surf dans les meilleures conditions',
      },
      {
        'id': 12,
        'nom': 'Centre de Plongée',
        'type': 'Plongée sous-marine',
        'description':
            'Centre de plongée certifié PADI offrant des excursions et formations de plongée dans l\'océan Atlantique.',
        'adresse': 'Marina d\'Agadir, Agadir',
        'prix': 400,
        'prixMin': 300,
        'prixMax': 600,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 30.4300,
        'longitude': -9.6000,
        'ville': 'Agadir',
        'categorie': 'Sports nautiques',
        'equipements': [
          'Équipement de plongée',
          'Bateau',
          'Compresseur',
          'Salle de cours',
        ],
        'services': [
          'Plongée découverte',
          'Formation PADI',
          'Excursions',
          'Photographie sous-marine',
        ],
        'horaires': '8h00 - 17h00',
        'telephone': '+212 5 28 23 45 67',
        'email': 'plongee@agadir-diving.ma',
        'siteWeb': 'www.agadir-diving.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Allemand'],
        'note': 'Explorez les fonds marins d\'Agadir',
      },
    ],
    'Tanger': [
      {
        'id': 13,
        'nom': 'Service de Ferry',
        'type': 'Transport maritime',
        'description':
            'Service de ferry pour traverser le détroit de Gibraltar vers l\'Espagne avec réservation en ligne.',
        'adresse': 'Port de Tanger, Tanger',
        'prix': 500,
        'prixMin': 400,
        'prixMax': 800,
        'devise': 'MAD',
        'notesMoyennes': 4.3,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 35.7595,
        'longitude': -5.8339,
        'ville': 'Tanger',
        'categorie': 'Transport',
        'equipements': ['Ferry moderne', 'Restaurant', 'WiFi', 'Parking'],
        'services': [
          'Traversée Tanger-Tarifa',
          'Réservation en ligne',
          'Transport véhicules',
          'Service VIP',
        ],
        'horaires': '6h00 - 22h00',
        'telephone': '+212 5 39 12 34 56',
        'email': 'ferry@tanger-maritime.ma',
        'siteWeb': 'www.tanger-maritime.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol'],
        'note': 'Traversée confortable vers l\'Espagne',
      },
      {
        'id': 14,
        'nom': 'Bureau de Change',
        'type': 'Services financiers',
        'description':
            'Bureau de change professionnel avec les meilleurs taux de change et service sécurisé.',
        'adresse': 'Boulevard Pasteur, Tanger',
        'prix': 0,
        'prixMin': 0,
        'prixMax': 0,
        'devise': 'MAD',
        'notesMoyennes': 4.5,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 35.7600,
        'longitude': -5.8300,
        'ville': 'Tanger',
        'categorie': 'Services financiers',
        'equipements': ['Coffre-fort', 'Comptoir sécurisé', 'WiFi', 'Parking'],
        'services': [
          'Change de devises',
          'Transfert d\'argent',
          'Cartes prépayées',
          'Service 24h/24',
        ],
        'horaires': '8h00 - 20h00',
        'telephone': '+212 5 39 23 45 67',
        'email': 'change@tanger-finance.ma',
        'siteWeb': 'www.tanger-finance.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Espagnol'],
        'note': 'Change de devises sécurisé à Tanger',
      },
    ],
    'Chefchaouen': [
      {
        'id': 15,
        'nom': 'Randonnée Montagne',
        'type': 'Randonnée',
        'description':
            'Guides de randonnée expérimentés pour explorer les montagnes du Rif et découvrir la nature préservée.',
        'adresse': 'Place Outa el Hammam, Chefchaouen',
        'prix': 150,
        'prixMin': 100,
        'prixMax': 250,
        'devise': 'MAD',
        'notesMoyennes': 4.8,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 35.1714,
        'longitude': -5.2696,
        'ville': 'Chefchaouen',
        'categorie': 'Randonnée',
        'equipements': [
          'Équipement de randonnée',
          'Cartes',
          'Jumelles',
          'Trousse de secours',
        ],
        'services': [
          'Randonnées guidées',
          'Observation nature',
          'Photographie',
          'Pique-nique',
        ],
        'horaires': '7h00 - 17h00',
        'telephone': '+212 5 39 34 56 78',
        'email': 'randonnee@chefchaouen-nature.ma',
        'siteWeb': 'www.chefchaouen-nature.ma',
        'langues': ['Français', 'Arabe', 'Anglais', 'Espagnol'],
        'note': 'Découvrez la beauté naturelle du Rif',
      },
    ],
    'Essaouira': [
      {
        'id': 16,
        'nom': 'École de Kitesurf',
        'type': 'Sports nautiques',
        'description':
            'École de kitesurf avec conditions idéales et moniteurs certifiés pour tous niveaux.',
        'adresse': 'Plage d\'Essaouira, Essaouira',
        'prix': 300,
        'prixMin': 250,
        'prixMax': 450,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 31.5085,
        'longitude': -9.7595,
        'ville': 'Essaouira',
        'categorie': 'Sports',
        'equipements': ['Voiles de kitesurf', 'Planches', 'Harnais', 'Casques'],
        'services': [
          'Cours de kitesurf',
          'Location matériel',
          'Compétitions',
          'Sorties en mer',
        ],
        'horaires': '9h00 - 18h00',
        'telephone': '+212 5 24 45 67 89',
        'email': 'kitesurf@essaouira-sports.ma',
        'siteWeb': 'www.essaouira-sports.ma',
        'langues': ['Français', 'Anglais', 'Arabe', 'Allemand'],
        'note': 'Conditions parfaites pour le kitesurf à Essaouira',
      },
      {
        'id': 17,
        'nom': 'Atelier de Musique',
        'type': 'Arts',
        'description':
            'Atelier de musique traditionnelle marocaine avec instruments authentiques et cours de Gnaoua.',
        'adresse': 'Médina d\'Essaouira, Essaouira',
        'prix': 100,
        'prixMin': 80,
        'prixMax': 150,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 31.5100,
        'longitude': -9.7600,
        'ville': 'Essaouira',
        'categorie': 'Arts',
        'equipements': [
          'Instruments traditionnels',
          'Salle de cours',
          'Enregistrement',
          'Bibliothèque musicale',
        ],
        'services': [
          'Cours de Gnaoua',
          'Instruments traditionnels',
          'Enregistrement',
          'Concerts',
        ],
        'horaires': '10h00 - 18h00',
        'telephone': '+212 5 24 56 78 90',
        'email': 'musique@essaouira-arts.ma',
        'siteWeb': 'www.essaouira-arts.ma',
        'langues': ['Français', 'Arabe', 'Anglais'],
        'note': 'Découvrez la musique traditionnelle marocaine',
      },
    ],
  };

  // Obtenir les services par ville
  List<Map<String, dynamic>> getServicesByCity(String cityName) {
    return servicesByCity[cityName] ?? [];
  }

  // Obtenir tous les services
  List<Map<String, dynamic>> getAllServices() {
    List<Map<String, dynamic>> allServices = [];
    servicesByCity.values.forEach((services) {
      allServices.addAll(services);
    });
    return allServices;
  }

  // Rechercher des services
  List<Map<String, dynamic>> searchServices(String query) {
    final allServices = getAllServices();
    return allServices.where((service) {
      final name = service['nom']?.toString().toLowerCase() ?? '';
      final type = service['type']?.toString().toLowerCase() ?? '';
      final description =
          service['description']?.toString().toLowerCase() ?? '';
      final city = service['ville']?.toString().toLowerCase() ?? '';
      final searchQuery = query.toLowerCase();

      return name.contains(searchQuery) ||
          type.contains(searchQuery) ||
          description.contains(searchQuery) ||
          city.contains(searchQuery);
    }).toList();
  }

  // Obtenir les types de services disponibles
  List<String> getServiceTypes() {
    return [
      'Spa et bien-être',
      'Visites guidées',
      'Restaurant',
      'Hammam',
      'Artisanat',
      'Transport',
      'Traduction',
      'Événementiel',
      'Guide touristique',
      'Sports nautiques',
      'Randonnée',
      'Arts',
      'Services financiers',
      'Transport maritime',
    ];
  }

  // Obtenir les catégories de services
  List<String> getServiceCategories() {
    return [
      'Bien-être',
      'Tourisme',
      'Restauration',
      'Bien-être traditionnel',
      'Artisanat',
      'Transport',
      'Services professionnels',
      'Événementiel',
      'Tourisme culturel',
      'Sports',
      'Sports nautiques',
      'Randonnée',
      'Arts',
      'Services financiers',
    ];
  }
}
