class MoroccanEventsService {
  static final MoroccanEventsService _instance = MoroccanEventsService._internal();
  factory MoroccanEventsService() => _instance;
  MoroccanEventsService._internal();

  // Événements par ville avec détails complets
  Map<String, List<Map<String, dynamic>>> get eventsByCity => {
    'Casablanca': [
      {
        'id': 1,
        'nom': 'Festival de Jazz de Casablanca',
        'type': 'Festival de musique',
        'description': 'Festival international de jazz réunissant des artistes du monde entier dans la capitale économique du Maroc.',
        'adresse': 'Théâtre Mohammed V, Casablanca',
        'prix': 200,
        'prixMin': 150,
        'prixMax': 500,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/casablanca_nightlife.jpg',
        'latitude': 33.5731,
        'longitude': -7.5898,
        'ville': 'Casablanca',
        'categorie': 'Musique',
        'dateDebut': '2024-06-15',
        'dateFin': '2024-06-22',
        'heureDebut': '20h00',
        'heureFin': '23h00',
        'organisateur': 'Association Jazz Casablanca',
        'capacite': 2000,
        'langues': ['Français', 'Anglais', 'Arabe'],
        'equipements': ['Sonorisation', 'Éclairage', 'Parking', 'Restaurant'],
        'services': ['Billetterie en ligne', 'Parking gratuit', 'Restauration', 'Boutique souvenirs'],
        'note': 'Événement incontournable pour les amateurs de jazz',
      },
      {
        'id': 2,
        'nom': 'Salon International de l\'Artisanat',
        'type': 'Salon professionnel',
        'description': 'Grande exposition d\'artisanat marocain traditionnel et contemporain avec des artisans de tout le pays.',
        'adresse': 'Palais des Expositions, Casablanca',
        'prix': 50,
        'prixMin': 30,
        'prixMax': 100,
        'devise': 'MAD',
        'notesMoyennes': 4.5,
        'imageUrl': 'assets/images/activities/casablanca_art_gallery.jpg',
        'latitude': 33.5800,
        'longitude': -7.6000,
        'ville': 'Casablanca',
        'categorie': 'Artisanat',
        'dateDebut': '2024-04-10',
        'dateFin': '2024-04-20',
        'heureDebut': '9h00',
        'heureFin': '19h00',
        'organisateur': 'Ministère de l\'Artisanat',
        'capacite': 5000,
        'langues': ['Français', 'Arabe', 'Anglais'],
        'equipements': ['Stands d\'exposition', 'Parking', 'Restauration', 'WiFi'],
        'services': ['Visites guidées', 'Ateliers', 'Dégustations', 'Vente directe'],
        'note': 'Découvrez l\'artisanat marocain dans toute sa splendeur',
      },
    ],
    'Marrakech': [
      {
        'id': 3,
        'nom': 'Festival International du Film de Marrakech',
        'type': 'Festival de cinéma',
        'description': 'Festival de cinéma de renommée internationale avec projections, masterclasses et cérémonies de remise de prix.',
        'adresse': 'Palais des Congrès, Marrakech',
        'prix': 100,
        'prixMin': 80,
        'prixMax': 300,
        'devise': 'MAD',
        'notesMoyennes': 4.8,
        'imageUrl': 'assets/images/activities/medina_tour.jpg',
        'latitude': 31.6258,
        'longitude': -7.9891,
        'ville': 'Marrakech',
        'categorie': 'Cinéma',
        'dateDebut': '2024-11-29',
        'dateFin': '2024-12-07',
        'heureDebut': '19h00',
        'heureFin': '23h00',
        'organisateur': 'Fondation du Festival de Marrakech',
        'capacite': 3000,
        'langues': ['Français', 'Anglais', 'Arabe'],
        'equipements': ['Salles de projection', 'Sonorisation', 'Éclairage', 'Parking'],
        'services': ['Projections gratuites', 'Rencontres avec les réalisateurs', 'Cocktails', 'Boutique'],
        'note': 'Festival de cinéma de renommée mondiale',
      },
      {
        'id': 4,
        'nom': 'Festival des Arts Populaires',
        'type': 'Festival culturel',
        'description': 'Festival traditionnel mettant en valeur les arts populaires marocains avec spectacles, danses et musiques.',
        'adresse': 'Place Jemaa el-Fnaa, Marrakech',
        'prix': 0,
        'prixMin': 0,
        'prixMax': 0,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 31.6258,
        'longitude': -7.9891,
        'ville': 'Marrakech',
        'categorie': 'Culture',
        'dateDebut': '2024-07-15',
        'dateFin': '2024-07-25',
        'heureDebut': '18h00',
        'heureFin': '22h00',
        'organisateur': 'Association des Arts Populaires',
        'capacite': 10000,
        'langues': ['Arabe', 'Français', 'Berbère'],
        'equipements': ['Scène en plein air', 'Sonorisation', 'Éclairage', 'Sécurité'],
        'services': ['Spectacles gratuits', 'Ateliers', 'Dégustations', 'Boutique artisanale'],
        'note': 'Immersion dans la culture marocaine authentique',
      },
    ],
    'Rabat': [
      {
        'id': 5,
        'nom': 'Festival Mawazine',
        'type': 'Festival de musique',
        'description': 'Grand festival de musique internationale avec des stars mondiales et des artistes marocains.',
        'adresse': 'Village Mawazine, Rabat',
        'prix': 300,
        'prixMin': 200,
        'prixMax': 800,
        'devise': 'MAD',
        'notesMoyennes': 4.9,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 34.0209,
        'longitude': -6.8416,
        'ville': 'Rabat',
        'categorie': 'Musique',
        'dateDebut': '2024-05-24',
        'dateFin': '2024-06-01',
        'heureDebut': '20h00',
        'heureFin': '01h00',
        'organisateur': 'Fondation Mawazine',
        'capacite': 15000,
        'langues': ['Français', 'Anglais', 'Arabe'],
        'equipements': ['Scène géante', 'Sonorisation professionnelle', 'Éclairage', 'Parking'],
        'services': ['Billetterie en ligne', 'Parking sécurisé', 'Restauration', 'Boutique'],
        'note': 'Le plus grand festival de musique du Maroc',
      },
      {
        'id': 6,
        'nom': 'Salon International du Livre',
        'type': 'Salon littéraire',
        'description': 'Grande foire du livre avec auteurs, éditeurs et conférences littéraires.',
        'adresse': 'Palais des Expositions, Rabat',
        'prix': 20,
        'prixMin': 15,
        'prixMax': 50,
        'devise': 'MAD',
        'notesMoyennes': 4.4,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 34.0250,
        'longitude': -6.8350,
        'ville': 'Rabat',
        'categorie': 'Littérature',
        'dateDebut': '2024-02-08',
        'dateFin': '2024-02-18',
        'heureDebut': '9h00',
        'heureFin': '20h00',
        'organisateur': 'Ministère de la Culture',
        'capacite': 8000,
        'langues': ['Français', 'Arabe', 'Anglais', 'Espagnol'],
        'equipements': ['Stands d\'exposition', 'Salles de conférence', 'Parking', 'WiFi'],
        'services': ['Conférences', 'Dédicaces', 'Ateliers', 'Vente de livres'],
        'note': 'Rendez-vous incontournable des amateurs de littérature',
      },
    ],
    'Fès': [
      {
        'id': 7,
        'nom': 'Festival de Musique Sacrée',
        'type': 'Festival spirituel',
        'description': 'Festival de musique sacrée du monde entier dans la ville spirituelle du Maroc.',
        'adresse': 'Médina de Fès, Fès',
        'prix': 150,
        'prixMin': 100,
        'prixMax': 300,
        'devise': 'MAD',
        'notesMoyennes': 4.8,
        'imageUrl': 'assets/images/activities/medina_fes.jpg',
        'latitude': 34.0581,
        'longitude': -4.9730,
        'ville': 'Fès',
        'categorie': 'Spirituel',
        'dateDebut': '2024-06-14',
        'dateFin': '2024-06-22',
        'heureDebut': '19h00',
        'heureFin': '22h00',
        'organisateur': 'Fondation Esprit de Fès',
        'capacite': 3000,
        'langues': ['Français', 'Arabe', 'Anglais'],
        'equipements': ['Scènes historiques', 'Sonorisation', 'Éclairage', 'Sécurité'],
        'services': ['Concerts', 'Conférences', 'Visites guidées', 'Boutique'],
        'note': 'Expérience spirituelle unique dans la médina millénaire',
      },
      {
        'id': 8,
        'nom': 'Festival des Arts de la Calligraphie',
        'type': 'Festival artistique',
        'description': 'Exposition et démonstrations de calligraphie arabe et berbère par des maîtres calligraphes.',
        'adresse': 'Palais Dar Batha, Fès',
        'prix': 30,
        'prixMin': 20,
        'prixMax': 60,
        'devise': 'MAD',
        'notesMoyennes': 4.5,
        'imageUrl': 'assets/images/activities/cultural_heritage.jpg',
        'latitude': 34.0645,
        'longitude': -4.9738,
        'ville': 'Fès',
        'categorie': 'Art',
        'dateDebut': '2024-03-20',
        'dateFin': '2024-03-30',
        'heureDebut': '10h00',
        'heureFin': '18h00',
        'organisateur': 'Association des Calligraphes',
        'capacite': 500,
        'langues': ['Arabe', 'Français', 'Anglais'],
        'equipements': ['Salles d\'exposition', 'Ateliers', 'Parking', 'WiFi'],
        'services': ['Expositions', 'Ateliers', 'Démonstrations', 'Vente d\'œuvres'],
        'note': 'Découvrez l\'art de la calligraphie arabe',
      },
    ],
    'Agadir': [
      {
        'id': 9,
        'nom': 'Festival Timitar',
        'type': 'Festival de musique',
        'description': 'Festival de musique amazighe et internationale sur la plage d\'Agadir.',
        'adresse': 'Plage d\'Agadir, Agadir',
        'prix': 100,
        'prixMin': 80,
        'prixMax': 200,
        'devise': 'MAD',
        'notesMoyennes': 4.6,
        'imageUrl': 'assets/images/activities/beach_activities.jpg',
        'latitude': 30.4278,
        'longitude': -9.5981,
        'ville': 'Agadir',
        'categorie': 'Musique',
        'dateDebut': '2024-07-12',
        'dateFin': '2024-07-15',
        'heureDebut': '19h00',
        'heureFin': '01h00',
        'organisateur': 'Association Timitar',
        'capacite': 20000,
        'langues': ['Berbère', 'Français', 'Anglais'],
        'equipements': ['Scène en plein air', 'Sonorisation', 'Éclairage', 'Sécurité'],
        'services': ['Concerts gratuits', 'Parking', 'Restauration', 'Boutique'],
        'note': 'Festival de musique amazighe sur la plage',
      },
      {
        'id': 10,
        'nom': 'Festival du Surf',
        'type': 'Compétition sportive',
        'description': 'Compétition internationale de surf avec des surfeurs du monde entier.',
        'adresse': 'Plage de Taghazout, Agadir',
        'prix': 0,
        'prixMin': 0,
        'prixMax': 0,
        'devise': 'MAD',
        'notesMoyennes': 4.7,
        'imageUrl': 'assets/images/activities/beach_activities.jpg',
        'latitude': 30.4500,
        'longitude': -9.6500,
        'ville': 'Agadir',
        'categorie': 'Sport',
        'dateDebut': '2024-09-15',
        'dateFin': '2024-09-22',
        'heureDebut': '8h00',
        'heureFin': '18h00',
        'organisateur': 'Fédération Marocaine de Surf',
        'capacite': 5000,
        'langues': ['Français', 'Anglais', 'Arabe'],
        'equipements': ['Scène de compétition', 'Sonorisation', 'Éclairage', 'Parking'],
        'services': ['Compétitions gratuites', 'Ateliers', 'Démonstrations', 'Boutique'],
        'note': 'Compétition de surf de niveau international',
      },
    ],
    'Tanger': [
      {
        'id': 11,
        'nom': 'Festival Tanjazz',
        'type': 'Festival de jazz',
        'description': 'Festival de jazz dans les lieux historiques de Tanger avec des artistes internationaux.',
        'adresse': 'Ville de Tanger, Tanger',
        'prix': 150,
        'prixMin': 100,
        'prixMax': 300,
        'devise': 'MAD',
        'notesMoyennes': 4.5,
        'imageUrl': 'assets/images/activities/kasbah_tanger.jpg',
        'latitude': 35.7595,
        'longitude': -5.8339,
        'ville': 'Tanger',
        'categorie': 'Musique',
        'dateDebut': '2024-09-05',
        'dateFin': '2024-09-08',
        'heureDebut': '19h00',
        'heureFin': '23h00',
        'organisateur': 'Association Tanjazz',
        'capacite': 2000,
        'langues': ['Français', 'Anglais', 'Arabe'],
        'equipements': ['Lieux historiques', 'Sonorisation', 'Éclairage', 'Parking'],
        'services': ['Concerts', 'Visites guidées', 'Restauration', 'Boutique'],
        'note': 'Jazz dans les lieux historiques de Tanger',
      },
    ],
    'Chefchaouen': [
      {
        'id': 12,
        'nom': 'Festival des Arts de la Montagne',
        'type': 'Festival culturel',
        'description': 'Festival mettant en valeur les arts et traditions des montagnes du Rif.',
        'adresse': 'Médina de Chefchaouen, Chefchaouen',
        'prix': 50,
        'prixMin': 30,
        'prixMax': 100,
        'devise': 'MAD',
        'notesMoyennes': 4.4,
        'imageUrl': 'assets/images/activities/medina_tetouan.jpg',
        'latitude': 35.1716,
        'longitude': -5.2696,
        'ville': 'Chefchaouen',
        'categorie': 'Culture',
        'dateDebut': '2024-08-10',
        'dateFin': '2024-08-15',
        'heureDebut': '18h00',
        'heureFin': '22h00',
        'organisateur': 'Association des Arts du Rif',
        'capacite': 1000,
        'langues': ['Berbère', 'Arabe', 'Français'],
        'equipements': ['Scène en plein air', 'Sonorisation', 'Éclairage', 'Sécurité'],
        'services': ['Spectacles', 'Ateliers', 'Dégustations', 'Boutique'],
        'note': 'Découvrez les arts traditionnels du Rif',
      },
    ],
    'Essaouira': [
      {
        'id': 13,
        'nom': 'Festival Gnaoua et Musiques du Monde',
        'type': 'Festival de musique',
        'description': 'Festival de musique Gnaoua et musiques du monde sur la plage d\'Essaouira.',
        'adresse': 'Plage d\'Essaouira, Essaouira',
        'prix': 200,
        'prixMin': 150,
        'prixMax': 400,
        'devise': 'MAD',
        'notesMoyennes': 4.8,
        'imageUrl': 'assets/images/activities/beach_activities.jpg',
        'latitude': 31.5085,
        'longitude': -9.7595,
        'ville': 'Essaouira',
        'categorie': 'Musique',
        'dateDebut': '2024-06-27',
        'dateFin': '2024-06-30',
        'heureDebut': '19h00',
        'heureFin': '01h00',
        'organisateur': 'Association Gnaoua',
        'capacite': 15000,
        'langues': ['Arabe', 'Français', 'Anglais'],
        'equipements': ['Scène en plein air', 'Sonorisation', 'Éclairage', 'Sécurité'],
        'services': ['Concerts', 'Ateliers', 'Parking', 'Restauration'],
        'note': 'Festival de musique Gnaoua de renommée mondiale',
      },
    ],
  };

  // Obtenir les événements par ville
  List<Map<String, dynamic>> getEventsByCity(String cityName) {
    return eventsByCity[cityName] ?? [];
  }

  // Obtenir tous les événements
  List<Map<String, dynamic>> getAllEvents() {
    List<Map<String, dynamic>> allEvents = [];
    eventsByCity.values.forEach((events) {
      allEvents.addAll(events);
    });
    return allEvents;
  }

  // Rechercher des événements
  List<Map<String, dynamic>> searchEvents(String query) {
    final allEvents = getAllEvents();
    return allEvents.where((event) {
      final name = event['nom']?.toString().toLowerCase() ?? '';
      final type = event['type']?.toString().toLowerCase() ?? '';
      final description = event['description']?.toString().toLowerCase() ?? '';
      final city = event['ville']?.toString().toLowerCase() ?? '';
      final searchQuery = query.toLowerCase();
      
      return name.contains(searchQuery) ||
             type.contains(searchQuery) ||
             description.contains(searchQuery) ||
             city.contains(searchQuery);
    }).toList();
  }

  // Obtenir les types d'événements disponibles
  List<String> getEventTypes() {
    return ['Festival de musique', 'Salon professionnel', 'Festival de cinéma', 'Festival culturel',
            'Festival spirituel', 'Festival artistique', 'Compétition sportive', 'Salon littéraire'];
  }

  // Obtenir les catégories d'événements
  List<String> getEventCategories() {
    return ['Musique', 'Artisanat', 'Cinéma', 'Culture', 'Spirituel', 'Art', 'Sport', 'Littérature'];
  }
}
